### ISSUE TITLE
Assertion failure in LocationManagerCorrelatedReader.

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#144]
To reproduce, run escjava2 on
escjava.ast.GeneralizedQuantifiedExpr.childAt.

I've also seen the same exception on some user code
that was sent to me.

escjava.ast.GeneralizedQuantifiedExpr: childAt(int) ...
------------------------------------------------------------------------
Exception in thread "main"
javafe.util.AssertionFailureException: streamId denotes
a whole file location
    at javafe.util.Assert.fail(Assert.java:14)
    at
javafe.util.LocationManagerCorrelatedReader.makeLocation(LocationManagerCorrelatedReader.java:216)
    at javafe.util.Location.make(Location.java:207)
    at
escjava.translate.UniqName.suffixToLoc(UniqName.java:94)
    at
escjava.translate.UniqName.suffixToLoc(UniqName.java:84)
    at escjava.translate.ErrorMsg.getLoc(ErrorMsg.java:526)
    at
escjava.translate.ErrorMsg.printErrorMessage(ErrorMsg.java:201)
    at escjava.translate.ErrorMsg.print(ErrorMsg.java:46)
    at escjava.Main.processRoutineDecl(Main.java:722)
    at escjava.Main.processTypeDeclElem(Main.java:501)
    at escjava.Main.processTD(Main.java:464)
    at escjava.Main.handleTD(Main.java:340)
    at javafe.SrcTool.handleCU(SrcTool.java:249)
    at escjava.Main.handleCU(Main.java:301)
    at javafe.SrcTool.handleAllCUs(SrcTool.java:207)
    at javafe.SrcTool.frontEndToolProcessing(SrcTool.java:143)
    at javafe.FrontEndTool.run(FrontEndTool.java:204)
    at escjava.Main.compile(Main.java:165)
    at escjava.Main.main(Main.java:140)

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
