### ISSUE TITLE
Failures with recent java 7

### ISSUE THREAD

**Issue by layus** [OpenJML/OpenJML#440]
Hi,

With recent versions of java 7, be it openjdk or Sun's version, I experience the following issue:
I have seen similar bug reports on openjml sourceforge bug tracker.

```
$ openjml -esc ...
openjml.jar(specs17/java/lang/Class.jml):31: error: The method java.lang.Class.Class() is a Java method (neither ghost nor model) but does not match any methods in the corresponding Java class.
    private Class();
            ^
1 error
```

Now, the signature of java.lang.Class() has chaged to Java.lang.Class(ClassLoader loader) with commit https://github.com/dmlloyd/openjdk/commit/f440464b7829b38bdb57aa4e9c7954a3dd3b7074.
Two questions: 1) How can we make a quick and dirty fix for this ? and 2) How can we update openjml to integrate this ?

Modifying spec17/java/lang/Class.jml in openjml.jar to reflect the changes fixes the issue, but create/reveals another one:

```
Proving methods in HelloWorld
Starting proof of HelloWorld.HelloWorld() with prover z3_4_3
Internal JML bug - please report.  BuildOpenJML-20150406-REV3502
java.lang.InternalError: Currency data format is incorrect
	at java.util.Currency$1.run(Currency.java:210)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.Currency.<clinit>(Currency.java:196)
	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:566)
	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:94)
	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:157)
	at java.util.Formatter.getZero(Formatter.java:2251)
	at java.util.Formatter.<init>(Formatter.java:1877)
	at java.util.Formatter.<init>(Formatter.java:1898)
	at java.lang.String.format(String.java:2792)
	at org.jmlspecs.openjml.esc.MethodProverSMT.setBenchmark(MethodProverSMT.java:1234)
	at org.jmlspecs.openjml.esc.MethodProverSMT.prove(MethodProverSMT.java:297)
	at org.jmlspecs.openjml.esc.JmlEsc.doMethod(JmlEsc.java:247)
	at org.jmlspecs.openjml.esc.JmlEsc.visitMethodDef(JmlEsc.java:163)
	at org.jmlspecs.openjml.JmlTreeScanner.visitJmlMethodDecl(JmlTreeScanner.java:174)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1072)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
	at com.sun.tools.javac.tree.TreeScanner.visitClassDef(TreeScanner.java:80)
	at org.jmlspecs.openjml.esc.JmlEsc.visitClassDef(JmlEsc.java:132)
	at org.jmlspecs.openjml.JmlTreeScanner.visitJmlClassDecl(JmlTreeScanner.java:70)
	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1012)
	at org.jmlspecs.openjml.esc.JmlEsc.check(JmlEsc.java:107)
	at org.jmlspecs.openjml.JmlCompiler.esc(JmlCompiler.java:618)
	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:385)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:866)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:662)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:835)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	at com.sun.tools.javac.main.Main.compile(Main.java:353)
	at org.jmlspecs.openjml.Main.compile(Main.java:533)
	at com.sun.tools.javac.main.Main.compile(Main.java:342)
	at com.sun.tools.javac.main.Main.compile(Main.java:333)
	at org.jmlspecs.openjml.Main.execute(Main.java:376)
	at org.jmlspecs.openjml.Main.execute(Main.java:334)
	at org.jmlspecs.openjml.Main.execute(Main.java:321)
	at org.jmlspecs.openjml.Main.main(Main.java:293)
ENDING with exit code 4
```

This is as much as I found for now. Any help appreciated.

**Comment by jsinglet** [comment]
The highest compatible JDK at the moment is Java 1.7.0_79. Are you by chance running PSU (7u80)? It reports a version string of 1.7.0_80.  The difference between 7u79 and 7u80 is summarized on Oracle's page: http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

> What is the difference between a Java CPU (7u79) and PSU (7u80) release?
Java SE Critical Patch Updates (CPU) contain fixes to security vulnerabilities and critical bug fixes. Oracle strongly recommends that all Java SE users upgrade to the latest CPU releases as they are made available. Most user should choose this release.
Java SE Patch Set Updates (PSU) contain all of the security fixes in the CPUs released up to that version, as well as additional non-critical fixes. Java PSU releases should only be used if you are being impacted by one of the additional bugs fixed in that version. 

Try using at most the 1.7.0_79 release to see if that helps.

**Comment by layus** [comment]
Writing everything down somehow cleared my mind. The currency issue is unrelated and was caused by a misconfiguration (property java.home != java home used to run openjml.jar).

My solution works like a charm for my basic HelloWorld example, so I may use that fix.
I will revert to 1.7.0_79 if I encounter more issues.

@jsinglet Thank you for your fast answer. Is there anything we can do to help make OpenJML support 1.7.0_80 ?

**Comment by jsinglet** [comment]
@layus No problem. I just happened to have hit that problem a few days earlier myself. I just tested out changing the spec, that works (and I don't get any further errors). I don't know if we have a precedent for supporting multiple versions of the *same* spec within a major java version (eg, 1.6, 1.7, etc). However as a quick and dirty hack, commenting the constructor out *works* too, and allows me to check small examples on 79 and 80, but I'd have to dig deeper to see what else this breaks. Any ideas @davidcok?

**Comment by layus** [comment]
As far as I can tell, removing the signature of a private constructor is unlikely to break anything.
On top of this, the signature does not have any  jml annotation.

We have have used the patched version (removed the Class() constructor signature from the jml) for some weeks now, and we had no issue related to that. Maybe we should just merge the fix ?

**Comment by slyubomirsky** [comment]
I ran into this same error just recently (building OpenJML from source using the PSF file from release V0.6.3), despite the commit noted above; commenting out the private constructor (as done above) also fixed the issue. Was the commit included in the release?

**Comment by layus** [comment]
The pull-request was not merged, and no release happened since this issue was posted.

**Comment by NikolaRaevski** [comment]
I encountered the exact same issue and again following the fellows' advice to comment out the constructor and it worked!

**Comment by davidcok** [comment]
Fixed, tested and pushed.
