### ISSUE TITLE
Crash of OpenJML with ESC on model program specification

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#445]
I am trying to check a model program specification with OpenJML (in ESC mode). When I do that it works on simple model program specifications, but one like the following 

```
/*@ public model_program { 
  @   normal_behavior
  @     ensures res != null && res instanceof ArrayList<S> 
  @          && res.size() == 2;
  @   res.add(0,p.run(first));
  @   res.add(1,p.run(second));
  @   return res;
  @ } @*/
public <S> ArrayList<S> mapToAl(Proc<T,S> p) {
    ArrayList<S> res = new ArrayList<S>(2);
    res.add(0, p.run(first));
    res.add(1, p.run(second));
    return res;
}
```

gives a crash, with output,as follows:

Internal JML bug - please report.  BuildOpenJML-20150406-REV3502
java.lang.AssertionError
    at com.sun.tools.javac.util.Assert.error(Assert.java:126)
    at com.sun.tools.javac.util.Assert.check(Assert.java:45)
    at com.sun.tools.javac.code.Scope.leave(Scope.java:150)
    at com.sun.tools.javac.comp.JmlAttr.visitJmlSpecificationCase(JmlAttr.java:2672)
    at org.jmlspecs.openjml.JmlTree$JmlSpecificationCase.accept(JmlTree.java:2391)
    at com.sun.tools.javac.comp.JmlAttr.visitJmlMethodSpecs(JmlAttr.java:2702)
    at org.jmlspecs.openjml.JmlTree$JmlMethodSpecs.accept(JmlTree.java:2063)
    at com.sun.tools.javac.comp.JmlAttr.visitBlock(JmlAttr.java:639)
    at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:781)
    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
    at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:480)
    at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:829)
    at com.sun.tools.javac.comp.JmlAttr.visitMethodDef(JmlAttr.java:901)
    at com.sun.tools.javac.comp.JmlAttr.visitJmlMethodDecl(JmlAttr.java:5246)
    at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1072)
    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
    at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:480)
    at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:3242)
    at com.sun.tools.javac.comp.JmlAttr.attribClassBody(JmlAttr.java:497)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:3165)
    at com.sun.tools.javac.comp.JmlAttr.attribClass(JmlAttr.java:419)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:3101)
    at com.sun.tools.javac.comp.Attr.attrib(Attr.java:3075)
    at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1193)
    at org.jmlspecs.openjml.JmlCompiler.attribute(JmlCompiler.java:465)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:866)
    at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:662)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:835)
    at com.sun.tools.javac.main.Main.compile(Main.java:439)
    at com.sun.tools.javac.main.Main.compile(Main.java:353)
    at org.jmlspecs.openjml.Main.compile(Main.java:533)
    at com.sun.tools.javac.main.Main.compile(Main.java:342)
    at com.sun.tools.javac.main.Main.compile(Main.java:333)
    at org.jmlspecs.openjml.Main.execute(Main.java:376)
    at org.jmlspecs.openjml.Main.execute(Main.java:334)
    at org.jmlspecs.openjml.Main.execute(Main.java:321)
    at org.jmlspecs.openjml.Main.main(Main.java:293)
ENDING with exit code 4

[Proc.java.txt](https://github.com/OpenJML/OpenJML/files/298997/Proc.java.txt)
[MapToAlClient.java.txt](https://github.com/OpenJML/OpenJML/files/299000/MapToAlClient.java.txt)
[Pair.java.txt](https://github.com/OpenJML/OpenJML/files/298998/Pair.java.txt)
[PMax.java.txt](https://github.com/OpenJML/OpenJML/files/298999/PMax.java.txt)

**Comment by davidcok** [comment]
With recent fixes, this test case no longer crashes. However, it appears to be syntactically ill-formed. The variable res is local to the procedure mapToA1 and thus not visible in the specification. The use of res in the specification has not corresponding declaration.

**Comment by davidcok** [comment]
Closing this. Test gitbug445a is a revision of this example that is syntactically correct but won't verify until model programs are implemented.
