### ISSUE TITLE
OpenJML null pointer exception in higher-order method

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#446]
When I try checking 
    /_@ also
      @   requires 0 <= i && i < a.length;
      @   assignable maxSeen;
      @   ensures maxSeen == Math.max(\old(maxSeen),a[i]); @_/
    public void run(Integer[] a, int i) {
        if (a[i] > maxSeen) {
            maxSeen = a[i];
        }
    }

I get an internal JML exception. The stack backtrace is below.  I'm attaching the files for this example.

.\APMax.java:9: warning: The prover cannot establish an assertion (PossiblyNullUnbox) in method run
        if (a[i] > maxSeen) {
            ^
error: An internal JML error occurred, possibly recoverable.  Please report the bug with as much information as you can.
  Reason: Internal exception: class java.lang.NullPointerException
  java.lang.NullPointerException
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.addPreConditions(JmlAssertionAdder.java:2959)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertMethodBodyNoInit(JmlAssertionAdder.java:953)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlMethodDecl(JmlAssertionAdder.java:9847)
    at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1072)
    at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:8795)
    at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1012)
    at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1181)
    at org.jmlspecs.openjml.esc.JmlEsc.check(JmlEsc.java:105)
    at org.jmlspecs.openjml.JmlCompiler.esc(JmlCompiler.java:618)
    at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:385)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:866)
    at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:662)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:835)
    at com.sun.tools.javac.main.Main.compile(Main.java:439)
    at com.sun.tools.javac.main.Main.compile(Main.java:353)
    at org.jmlspecs.openjml.Main.compile(Main.java:533)
    at com.sun.tools.javac.main.Main.compile(Main.java:342)
    at com.sun.tools.javac.main.Main.compile(Main.java:333)
    at org.jmlspecs.openjml.Main.execute(Main.java:376)
    at org.jmlspecs.openjml.Main.execute(Main.java:334)
    at org.jmlspecs.openjml.Main.execute(Main.java:321)
    at org.jmlspecs.openjml.Main.main(Main.java:293)

error: An internal JML error occurred, possibly recoverable.  Please report the bug with as much information as you can.
  Reason: Internal exception: class java.lang.NullPointerException
  java.lang.NullPointerException
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.applyHelper(JmlAssertionAdder.java:5800)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitApply(JmlAssertionAdder.java:5074)
    at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1321)
    at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1252)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitExec(JmlAssertionAdder.java:4231)
    at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1167)
    at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1181)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertMethodBodyNoInit(JmlAssertionAdder.java:972)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlMethodDecl(JmlAssertionAdder.java:9847)
    at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1072)
    at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:8795)
    at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1012)
    at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
    at org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1181)
    at org.jmlspecs.openjml.esc.JmlEsc.check(JmlEsc.java:105)
    at org.jmlspecs.openjml.JmlCompiler.esc(JmlCompiler.java:618)
    at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:385)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:866)
    at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:662)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:835)
    at com.sun.tools.javac.main.Main.compile(Main.java:439)
    at com.sun.tools.javac.main.Main.compile(Main.java:353)
    at org.jmlspecs.openjml.Main.compile(Main.java:533)
    at com.sun.tools.javac.main.Main.compile(Main.java:342)
    at com.sun.tools.javac.main.Main.compile(Main.java:333)
    at org.jmlspecs.openjml.Main.execute(Main.java:376)
    at org.jmlspecs.openjml.Main.execute(Main.java:334)
    at org.jmlspecs.openjml.Main.execute(Main.java:321)
    at org.jmlspecs.openjml.Main.main(Main.java:293)
2 errors
1 warning

[AProc.java.txt](https://github.com/OpenJML/OpenJML/files/299144/AProc.java.txt)
[APMax.java.txt](https://github.com/OpenJML/OpenJML/files/299141/APMax.java.txt)
[ForEachClient.java.txt](https://github.com/OpenJML/OpenJML/files/299142/ForEachClient.java.txt)
[ArrOps.java.txt](https://github.com/OpenJML/OpenJML/files/299143/ArrOps.java.txt)

**Comment by iconmaster5326** [comment]
What steps did you take to reproduce this issue? If done from the command line, what arguments did you give it to cause this?

**Comment by davidcok** [comment]
Has been resolved - the gitbug446 test holds this case and has been working for some time.
