### ISSUE TITLE
RAC Compiler results in error BuildOpenJML-20150406-REV3495

### ISSUE THREAD

**Issue by NikolaRaevski** [OpenJML/OpenJML#449]
Using Apache's commons-lang3-3.3.2.jar, trying to compile RAC of files containing the overloaded method -
 `org.apache.commons.lang3.Validate.notNull(T  object, String message, Object... values)`,
results in BuildOpenJML-20150406-REV3495 bug:
```
Internal JML bug - please report.  BuildOpenJML-20150406-REV3495
java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.util.Assert.check(Assert.java:45)
	at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:597)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1321)...
```

**Comment by davidcok** [comment]
Fix in V-21-0.18
