### ISSUE TITLE
V0.8.1 Exception

### ISSUE THREAD

**Issue by Yevhenii-Melnyk** [OpenJML/OpenJML#482]
Hello. Tried this release and got instant exception. Release 7 seems to work.

A JmlSingleton expects a JmlTreeVisitor, not a class com.sun.tools.javac.tree.TreeCopier
Internal JML bug - please report.  BuildOpenJML-jdk8u-20161102
java.lang.NullPointerException
        at com.sun.tools.javac.util.ListBuffer.append(ListBuffer.java:127)
        at com.sun.tools.javac.tree.TreeCopier.copy(TreeCopier.java:77)
        at com.sun.tools.javac.tree.TreeCopier.visitMethodInvocation(TreeCopier.java:269)
        at com.sun.tools.javac.tree.TreeCopier.visitMethodInvocation(TreeCopier.java:1)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
        at com.sun.tools.javac.tree.TreeCopier.copy(TreeCopier.java:58)
        at com.sun.tools.javac.tree.TreeCopier.copy(TreeCopier.java:51)
        at com.sun.tools.javac.comp.DeferredAttr.attribSpeculative(DeferredAttr.java:363)
        at com.sun.tools.javac.comp.Attr.isBooleanOrNumeric(Attr.java:1462)
        at com.sun.tools.javac.comp.JmlAttr.isBooleanOrNumeric(JmlAttr.java:5909)
        at com.sun.tools.javac.comp.Attr.isBooleanOrNumeric(Attr.java:1458)
        at com.sun.tools.javac.comp.JmlAttr.isBooleanOrNumeric(JmlAttr.java:5909)
        at com.sun.tools.javac.comp.Attr.visitConditional(Attr.java:1413)
        at com.sun.tools.javac.tree.JCTree$JCConditional.accept(JCTree.java:1237)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:608)
        at com.sun.tools.javac.comp.JmlAttr.attribExpr(JmlAttr.java:5597)
        at com.sun.tools.javac.comp.JmlAttr.visitJmlMethodClauseExpr(JmlAttr.java:2657)
        at org.jmlspecs.openjml.JmlTree$JmlMethodClauseExpr.accept(JmlTree.java:1999)
        at com.sun.tools.javac.comp.JmlAttr.visitJmlSpecificationCase(JmlAttr.java:2846)
        at org.jmlspecs.openjml.JmlTree$JmlSpecificationCase.accept(JmlTree.java:2588)
        at com.sun.tools.javac.comp.JmlAttr.visitJmlMethodSpecs(JmlAttr.java:2884)
        at org.jmlspecs.openjml.JmlTree$JmlMethodSpecs.accept(JmlTree.java:2254)
        at com.sun.tools.javac.comp.JmlAttr.checkMethodSpecsDirectly(JmlAttr.java:1289)
        at com.sun.tools.javac.comp.JmlAttr.visitMethodDef(JmlAttr.java:978)
        at com.sun.tools.javac.comp.JmlAttr.visitJmlMethodDecl(JmlAttr.java:5500)
        at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1131)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:635)
        at com.sun.tools.javac.comp.JmlAttr.attribStat(JmlAttr.java:531)
        at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4352)
        at com.sun.tools.javac.comp.JmlAttr.attribClassBody(JmlAttr.java:515)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4260)
        at com.sun.tools.javac.comp.JmlAttr.attribClass(JmlAttr.java:420)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4189)
        at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4164)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1258)
        at org.jmlspecs.openjml.JmlCompiler.attribute(JmlCompiler.java:409)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
        at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:586)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
        at com.sun.tools.javac.main.Main.compile(Main.java:548)
        at com.sun.tools.javac.main.Main.compile(Main.java:409)
        at org.jmlspecs.openjml.Main.compile(Main.java:544)
        at com.sun.tools.javac.main.Main.compile(Main.java:398)
        at com.sun.tools.javac.main.Main.compile(Main.java:389)
        at org.jmlspecs.openjml.Main.execute(Main.java:381)
        at org.jmlspecs.openjml.Main.execute(Main.java:339)
        at org.jmlspecs.openjml.Main.execute(Main.java:326)
        at org.jmlspecs.openjml.Main.main(Main.java:298)
ENDING with exit code 4

**Comment by davidcok** [comment]
Please include the source file that is causing the problem so I can replicate the error and check that it is fixed in your context.

**Comment by davidcok** [comment]
I'd like to fix this. Did you close the bug report by accident or is it no longer an issue?

**Comment by Yevhenii-Melnyk** [comment]
The issue can be reproduced using this repo https://github.com/banthar/checkers  
I call jml like this:
java -cp "openjml.jar" org.jmlspecs.openjml.Main -dir "src/main"

**Comment by davidcok** [comment]
Fixed in commit b45e55edf8b965f0a03cf978d736df0634da8b71.
Will be in release 0.8.3
