### ISSUE TITLE
Internal bug unexpected tree \exists

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#497]
Running OpenJML 0.8.10 on a file gets various syntax errors and then an internal bug. I'm attaching a zip with the input file (IVec.java and the output of running the command line tool on it).

IVec.java:15: error: ')' expected
      @                            j <= i ==> src[j] != 0); @*/
                                                          ^
IVec.java:30: error: illegal start of type
      @       && (\exists int i; 0 <= i && i < right.length; 
              ^
IVec.java:30: error: <identifier> expected
      @       && (\exists int i; 0 <= i && i < right.length; 
                ^
IVec.java:31: error: <identifier> expected
      @                           right[i] == 0); @*/
                                               ^
IVec.java:30: error: cannot find symbol
      @       && (\exists int i; 0 <= i && i < right.length; 
                                               ^
  symbol:   variable right
  location: class IVec
IVec.java:31: error: cannot find symbol
      @                           right[i] == 0); @*/
                                  ^
  symbol:   variable right
  location: class IVec
IVec.java:30: error: unexpected type
      @       && (\exists int i; 0 <= i && i < right.length; 
                  ^
  required: class
  found:    value
Internal JML bug - please report.  BuildOpenJML-0.8.10-20170402
java.lang.AssertionError: Unexpected tree: \exists int i; 0 <= i && i < right.length; right[i] == 0 with kind: OTHER within: \exists int i; 0 <= i && i < right.length; right[i] == 0 with kind: OTHER
	at com.sun.tools.javac.util.Assert.error(Assert.java:133)
	at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.validateAnnotatedType(Attr.java:4680)
	at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitVarDef(Attr.java:4525)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
	at org.jmlspecs.openjml.JmlTree$JmlVariableDecl.accept(JmlTree.java:1273)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
	at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitMethodDef(Attr.java:4516)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1150)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitClassDef(Attr.java:4577)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1068)
	at com.sun.tools.javac.comp.Attr.validateTypeAnnotations(Attr.java:4475)
	at com.sun.tools.javac.code.TypeAnnotations$2.run(TypeAnnotations.java:142)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:155)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.comp.JmlEnter.main(JmlEnter.java:766)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:992)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:864)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:556)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.execute(Main.java:392)
	at org.jmlspecs.openjml.Main.execute(Main.java:350)
	at org.jmlspecs.openjml.Main.execute(Main.java:337)
	at org.jmlspecs.openjml.Main.main(Main.java:309)

[IVec-problem.zip](https://github.com/OpenJML/OpenJML/files/896041/IVec-problem.zip)

**Comment by davidcok** [comment]
The file does indeed have syntax errors - missing ) on line 13 and extra ; on line 29 - but it should not crash.
