### ISSUE TITLE
Internal JML bug

### ISSUE THREAD

**Issue by jhoenicke** [OpenJML/OpenJML#498]
This file [PriorityQueue.java](https://gist.github.com/jhoenicke/69e9076b42b6c30e2fcc10a3f2c79c17) triggers an Internal JML bug:

    Internal JML bug - please report.  BuildOpenJML-0.8.10-20170402
    java.lang.NullPointerException
            at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker.quicklyResolveMethod(DeferredAttr.java:1310)
            at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker.quicklyResolveMethod(DeferredAttr.java:1323)
            at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker.visitApply(DeferredAttr.java:1240)

**Comment by davidcok** [comment]
Fixed for the  0.8.11 release
