### ISSUE TITLE
Internal null pointer exception

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#499]
I tried running from the command line 
   openjml IntSet.java Interval.java
and got a null pointer exception internal error. I know that there is a syntax error on line 43 of Interval.java, but I'm reporting this so you can chase down the null pointer exception that occurs.

$ openjml IntSet.java Interval.java
Interval.java:43: error: Expected a declaration or a JML construct inside the JML annotation here
            //@ contains(i);
                ^
Internal JML bug - please report.  BuildOpenJML-0.8.10-20170402
java.lang.NullPointerException
	at com.sun.tools.javac.parser.JavacParser.parseStatementAsBlock(JavacParser.java:2484)
	at com.sun.tools.javac.parser.JavacParser.parseStatement(JavacParser.java:2604)
	at com.sun.tools.javac.parser.JmlParser.parseStatement(JmlParser.java:779)
	at com.sun.tools.javac.parser.JavacParser.blockStatement(JavacParser.java:2511)
	at com.sun.tools.javac.parser.JmlParser.blockStatement(JmlParser.java:512)
	at com.sun.tools.javac.parser.JavacParser.parseStatementAsBlock(JavacParser.java:2476)
	at com.sun.tools.javac.parser.JavacParser.parseStatement(JavacParser.java:2608)
	at com.sun.tools.javac.parser.JmlParser.parseStatement(JmlParser.java:779)
	at com.sun.tools.javac.parser.JavacParser.blockStatement(JavacParser.java:2511)
	at com.sun.tools.javac.parser.JmlParser.blockStatement(JmlParser.java:512)
	at com.sun.tools.javac.parser.JavacParser.blockStatements(JavacParser.java:2457)
	at com.sun.tools.javac.parser.JmlParser.blockStatements(JmlParser.java:478)
	at com.sun.tools.javac.parser.JavacParser.block(JavacParser.java:2428)
	at com.sun.tools.javac.parser.JavacParser.block(JavacParser.java:2442)
	at com.sun.tools.javac.parser.JavacParser.methodDeclaratorRest(JavacParser.java:3712)
	at com.sun.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3658)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceBodyDeclaration(JmlParser.java:901)
	at com.sun.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3562)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceBody(JmlParser.java:372)
	at com.sun.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3408)
	at com.sun.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3349)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceOrEnumDeclaration(JmlParser.java:306)
	at com.sun.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:3338)
	at com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:3278)
	at com.sun.tools.javac.parser.JmlParser.parseCompilationUnit(JmlParser.java:191)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:633)
	at org.jmlspecs.openjml.JmlCompiler.parse(JmlCompiler.java:123)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:670)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:960)
	at org.jmlspecs.openjml.JmlCompiler.parseFiles(JmlCompiler.java:243)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:864)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:556)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.execute(Main.java:392)
	at org.jmlspecs.openjml.Main.execute(Main.java:350)
	at org.jmlspecs.openjml.Main.execute(Main.java:337)
	at org.jmlspecs.openjml.Main.main(Main.java:309)
[IS-example.zip](https://github.com/OpenJML/OpenJML/files/907693/IS-example.zip)

**Comment by davidcok** [comment]
The problematic syntax error is on line 58 of Interval.java -- a missing { that makes the only content of the else-if block be a JML statement. Improved the parser so that such syntax includes all JML statements and the first Java statement.

Fixed for the  0.8.11 release
