### ISSUE TITLE
Internal JML bug: NullPointerException in TreeInfo.skipParens.

### ISSUE THREAD

**Issue by jhoenicke** [OpenJML/OpenJML#500]
Thanks for fixing the last bug so fast.  I now get another compiler bug in the next file Heap.java.  I built openjml from github master branch

I have three different variants of this class, but it appears the error is triggered in each of them.
http://www.informatik.uni-freiburg.de/~hoenicke/fm4j/heap-example.tar.gz

<details>

```
Internal JML bug - please report.  BuildOpenJML-20170413
java.lang.NullPointerException
        at com.sun.tools.javac.tree.TreeInfo.skipParens(TreeInfo.java:748)
        at com.sun.tools.javac.tree.TreeInfo.symbol(TreeInfo.java:851)
        at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:667)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
        at org.jmlspecs.openjml.JmlTree$JmlMethodInvocation.accept(JmlTree.java:1909)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:490)
        at com.sun.tools.javac.comp.TransTypes.visitVarDef(TransTypes.java:548)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
        at org.jmlspecs.openjml.JmlTree$JmlVariableDecl.accept(JmlTree.java:1273)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:134)
        at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:1007)
        at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:511)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
        at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1068)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:490)
        at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:1035)
        at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1496)
        at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:399)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
        at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:591)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.main.Main.compile(Main.java:410)
        at org.jmlspecs.openjml.Main.compile(Main.java:556)
        at com.sun.tools.javac.main.Main.compile(Main.java:399)
        at com.sun.tools.javac.main.Main.compile(Main.java:390)
        at org.jmlspecs.openjml.Main.execute(Main.java:392)
        at org.jmlspecs.openjml.Main.execute(Main.java:350)
        at org.jmlspecs.openjml.Main.execute(Main.java:337)
        at org.jmlspecs.openjml.Main.main(Main.java:309)
```

</details>

PS: These files are from an older lecture.  I'm not sure if I used the right syntax everywhere, but I think they compiled with an old version of jmlrac.  Some of the implementations may have an intentional bug that causes the contract to be violated in rare cases.

**Comment by davidcok** [comment]
Fixed in V0.8.11.  The problem was triggered by changes to the System.jml specs, in which 'old' clauses were now being used. That ran into unimplemented aspects of 'old' clauses. Rather than just revert the specifications, 'old' clauses are now implemented.
