### ISSUE TITLE
\forall giving java.lang.AssertionError

### ISSUE THREAD

**Issue by gnickst** [OpenJML/OpenJML#536]
When using the \forall macro, I receive an assertion error and a large stacktrace.

Example:
```
// Compile & run: java -jar $OJ/openjml.jar -compile test.java -rac && jml Test

class Test {

  //@requires \forall int i; 0 <= i && i < array.length-1; array[i] <= array[i+1];
  public static void doesNothingButRequiresSorted(int[] array) {
  }

  public static void main(String[] args) {
    int[] array0 = {0,1,2,3};
    int[] array1 = {0,1,2,-3};

    // Succeeds
    doesNothingButRequiresSorted(array0);
    // Fails
    doesNothingButRequiresSorted(array1);
  }
}
```
When compiled with `java -jar $OJ/openjml.jar -compile test.java -rac`, gives: 
```
Internal JML bug - please report.  BuildOpenJML-0.8.18-20170726
java.lang.AssertionError: _JML__tmp8
	at com.sun.tools.javac.comp.Lower.unbox(Lower.java:3177)
	at com.sun.tools.javac.comp.Lower.boxIfNeeded(Lower.java:3136)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.visitBinary(Lower.java:3367)
	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1785)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.visitWhileLoop(Lower.java:3572)
	at com.sun.tools.javac.tree.JCTree$JCWhileLoop.accept(JCTree.java:965)
	at org.jmlspecs.openjml.JmlTree$JmlWhileLoop.accept(JmlTree.java:1664)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
...
```

If I rewrite the forall conditions so that it doesn't use an expression as the upper bound of i, it works as expected. For example, instead of
```
//@requires \forall int i; 0 <= i && i < array.length-1; array[i] <= array[i+1];
```
I use
```
//@requires \forall int i; 1 <= i && i < array.length; array[i-1] <= array[i];
```

### Details: 

Input command: `java -jar $OJ/openjml.jar -compile test.java -rac`
OpenJML version: `openjml-0.8.18-20170726`
Java version: `1.8.0_101`

**Comment by davidcok** [comment]
Fixed in V0.8.20
