### ISSUE TITLE
Internal error when forgetting model in represents clause

### ISSUE THREAD

**Issue by HansvdLaan** [OpenJML/OpenJML#589]
When making some exercises for a course, I forgot add the model in a represents clause. 

Example how it looked:
```
public class A {
	//@ public model int a;
	//@ represents = 1 * 2 + 3;
}
```

It did give me a correct marker on the represents clause stating that : 
"Multiple markers at this line
	- Incorrectly formed or terminated store-reference near here
	- A represents clause must have a = or \such_that after the identifier"

However, it also produced an internal error:

`Internal JML bug - please report.  BuildOpenJML-20170830
java.lang.NullPointerException
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:618)
	at com.sun.tools.javac.comp.JmlAttr.attribExpr(JmlAttr.java:5978)
	at com.sun.tools.javac.comp.JmlAttr.visitJmlTypeClauseRepresents(JmlAttr.java:2665)
	at org.jmlspecs.openjml.JmlTree$JmlTypeClauseRepresents.accept(JmlTree.java:3594)
	at com.sun.tools.javac.comp.JmlAttr.attribClassBodySpecs(JmlAttr.java:594)
	at com.sun.tools.javac.comp.JmlAttr.attribClassBody(JmlAttr.java:547)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4284)
	at com.sun.tools.javac.comp.JmlAttr.attribClass(JmlAttr.java:425)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4213)
	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4188)
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1258)
	at org.jmlspecs.openjml.JmlCompiler.attribute(JmlCompiler.java:425)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:640)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:559)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.executeNS(Main.java:485)
	at org.jmlspecs.openjml.API.execute(API.java:215)
	at org.jmlspecs.openjml.eclipse.OpenJMLInterface.executeESCCommand(OpenJMLInterface.java:471)
	at org.jmlspecs.openjml.eclipse.Utils$2.run(Utils.java:353)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
ENDING with exit code 4
INTERNAL ERROR: return code = 4   Command: -command=esc -strictJML=false -purityCheck=true -show=false -prover=z3_4_4 -exec=/usr/bin/z3 -escMaxWarnings=2147483647 -trace=true -subexpressions=true -checkFeasibility=all -timeout=45 -code-math=java -verboseness=0 -nullableByDefault=false -no-internalSpecs -specspath /home/fmt/eclipse-workspace/JmlTestS4/src:/home/fmt/eclipse/java-oxygen/eclipse/configuration/org.eclipse.osgi/487/0/.cp/java8:/home/fmt/eclipse/java-oxygen/eclipse/configuration/org.eclipse.osgi/487/0/.cp/java7:/home/fmt/eclipse/java-oxygen/eclipse/configuration/org.eclipse.osgi/487/0/.cp/java6:/home/fmt/eclipse/java-oxygen/eclipse/configuration/org.eclipse.osgi/487/0/.cp/java5:/home/fmt/eclipse/java-oxygen/eclipse/configuration/org.eclipse.osgi/487/0/.cp/java4 -sourcepath /home/fmt/eclipse-workspace/JmlTestS4/src -no-internalRuntime -classpath /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/home/fmt/eclipse-workspace/JmlTestS4/src:/home/fmt/eclipse/java-oxygen/eclipse/configuration/org.eclipse.osgi/486/0/.cp/jmlruntime.jar /home/fmt/eclipse-workspace/JmlTestS4/src/abstraction/A.java 
`

**Comment by davidcok** [comment]
Fixed for 0.8.25
