### ISSUE TITLE
org.jmlspecs.models and java.lang.StackOverflowError

### ISSUE THREAD

**Issue by vmvasconcelos** [OpenJML/OpenJML#590]
$ uname -a
Darwin Arcanine.lan 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

$ java -jar /usr/local/opt/openjml/openjml.jar -version
openjml OpenJML-0.8.24-20171007

$ java -jar /usr/local/opt/openjml/openjml.jar -rac Sequence.java 
Note: /usr/local/opt/openjml/openjml.jar(specs18/java/util/Random.jml) uses internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.

$ java -cp .:/usr/local/opt/openjml/jmlruntime.jar Sequence
Exception in thread "main" java.lang.StackOverflowError
	at Sequence.abstractionFunction(Sequence.java:8)
	at Sequence._JML$model$theSequence(Sequence.java:7)
	at Sequence.abstractionFunction(Sequence.java:6)
	at Sequence._JML$model$theSequence(Sequence.java:7)
	at Sequence.abstractionFunction(Sequence.java:6)
        ...

$ cat Sequence.java 
import org.jmlspecs.models.JMLObjectSequence;
//@ model import org.jmlspecs.models.JMLObjectSequence;
class Sequence {
    private Object[] elems;
    private int size;
    //@ model instance JMLObjectSequence theSequence;
    //@ private represents theSequence <- abstractionFunction();
    private /*@ pure @*/ JMLObjectSequence abstractionFunction () {
	return JMLObjectSequence.convertFrom(elems, size);
    }
    Sequence() { elems = new Object[2]; }
    public static void main(String[] args) { Sequence s = new Sequence(); }
}

Note. This used to work perfectly well on the Mobius release

**Comment by davidcok** [comment]
The workaround for this problem is to declare abstractionFunction() as helper.
