### ISSUE TITLE
Operators bug in requires clauses

### ISSUE THREAD

**Issue by TheZxcv** [OpenJML/OpenJML#596]
# Operators bug in requires clauses

I have tried to compile the following snippets with the OpenJML compiler as shown below:
```bash
$ java -jar openjml.jar -compile -rac -- TestCase.java
```

Each of them causes a different compilation error (included).

## Versions
```bash
$ java -version
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1102-b2)
OpenJDK 64-Bit Server VM (build 25.152-b2, mixed mode)

$ java -jar openjml.jar -version
openjml OpenJML-0.8.24-20171007
```

## Test code
```java
public class TestCase {
    public int a = 1;

    //@ requires b >= +a;
    public void plus(int b) {}
}
```
<details>
  <summary>Compilation Error</summary>
<pre>
TestCase.java:4: error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
    //@ requires b >= +a;
                      ^
  Reason: Unexpected operation in Arithmetic.Math.rewriteUnary
error: An internal JML error occurred, possibly recoverable.  Please report the bug with as much information as you can.
  Reason: Internal exception: class java.lang.NullPointerException
  java.lang.NullPointerException
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.newTemp(JmlAssertionAdder.java:2150)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.newTemp(JmlAssertionAdder.java:2146)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitUnary(JmlAssertionAdder.java:9776)
  	at com.sun.tools.javac.tree.JCTree$JCUnary.accept(JCTree.java:1746)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1394)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitBinary(JmlAssertionAdder.java:9948)
  	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1785)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1394)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1513)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1526)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.addPreConditions(JmlAssertionAdder.java:3722)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertMethodBodyNoInit(JmlAssertionAdder.java:1046)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlMethodDecl(JmlAssertionAdder.java:12570)
  	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1137)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:11458)
  	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1053)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1301)
  	at org.jmlspecs.openjml.JmlCompiler.rac(JmlCompiler.java:573)
  	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:410)
  	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
  	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:652)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
  	at com.sun.tools.javac.main.Main.compile(Main.java:553)
  	at com.sun.tools.javac.main.Main.compile(Main.java:410)
  	at org.jmlspecs.openjml.Main.compile(Main.java:560)
  	at com.sun.tools.javac.main.Main.compile(Main.java:399)
  	at com.sun.tools.javac.main.Main.compile(Main.java:390)
  	at org.jmlspecs.openjml.Main.execute(Main.java:396)
  	at org.jmlspecs.openjml.Main.execute(Main.java:354)
  	at org.jmlspecs.openjml.Main.execute(Main.java:341)
  	at org.jmlspecs.openjml.Main.main(Main.java:313)
Note: openjml.jar(specs18/java/util/Random.jml) uses internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.
2 errors
</pre>
</details>

##
```java
public class TestCase {
    public int a = 1;

    //@ requires b >= Math.max(0, -1 * a);
    public void timesMinusOne(int b) {}
}
```
<details>
  <summary>Compilation Error</summary>
<pre>
Internal JML bug - please report.  BuildOpenJML-0.8.24-20171007
java.lang.AssertionError: _JML__tmp1
	at com.sun.tools.javac.comp.Lower.unbox(Lower.java:3177)
	at com.sun.tools.javac.comp.Lower.boxIfNeeded(Lower.java:3136)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.boxArgs(Lower.java:3112)
	at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3015)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.visitBinary(Lower.java:3367)
	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1785)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.visitAssign(Lower.java:3203)
	at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1686)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitExec(TreeTranslator.java:245)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitTry(TreeTranslator.java:218)
	at com.sun.tools.javac.comp.Lower.visitTry(Lower.java:3897)
	at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1173)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitMethodDef(TreeTranslator.java:145)
	at com.sun.tools.javac.comp.Lower.visitMethodDefInternal(Lower.java:2828)
	at com.sun.tools.javac.comp.Lower.visitMethodDef(Lower.java:2737)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1140)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.visitClassDef(Lower.java:2508)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1056)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2390)
	at com.sun.tools.javac.comp.Lower.translateTopLevelClass(Lower.java:3932)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1522)
	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:420)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:652)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:560)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.execute(Main.java:396)
	at org.jmlspecs.openjml.Main.execute(Main.java:354)
	at org.jmlspecs.openjml.Main.execute(Main.java:341)
	at org.jmlspecs.openjml.Main.main(Main.java:313)
</pre>
</details>

##
```java
public class TestCase {
    public int a = 1;

    //@ requires b >= Math.max(0, (int)(-1.0 * a));
    public void timesMinusOneFloat(int b) {}
}
```
<details>
  <summary>Compilation Error</summary>
<pre>
Method real_toint not found in Utils
org.jmlspecs.openjml.JmlInternalError: Method real_toint not found in Utils
	at org.jmlspecs.openjml.JmlTreeUtils.findUtilsMethod(JmlTreeUtils.java:298)
	at org.jmlspecs.openjml.JmlTreeUtils.makeUtilsMethodCall(JmlTreeUtils.java:1369)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitTypeCast(JmlAssertionAdder.java:10290)
	at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExprList(JmlAssertionAdder.java:1408)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitApply(JmlAssertionAdder.java:6427)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1394)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitBinary(JmlAssertionAdder.java:9948)
	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1785)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1394)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1513)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1526)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.addPreConditions(JmlAssertionAdder.java:3722)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertMethodBodyNoInit(JmlAssertionAdder.java:1046)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlMethodDecl(JmlAssertionAdder.java:12570)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1137)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:11458)
	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1053)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1301)
	at org.jmlspecs.openjml.JmlCompiler.rac(JmlCompiler.java:573)
	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:410)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:652)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:560)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.execute(Main.java:396)
	at org.jmlspecs.openjml.Main.execute(Main.java:354)
	at org.jmlspecs.openjml.Main.execute(Main.java:341)
	at org.jmlspecs.openjml.Main.main(Main.java:313)
error: An internal JML error occurred, possibly recoverable.  Please report the bug with as much information as you can.
  Reason: Method real_toint not found in Utils
  org.jmlspecs.openjml.JmlInternalError: Method real_toint not found in Utils
  	at org.jmlspecs.openjml.JmlTreeUtils.findUtilsMethod(JmlTreeUtils.java:298)
  	at org.jmlspecs.openjml.JmlTreeUtils.makeUtilsMethodCall(JmlTreeUtils.java:1369)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitTypeCast(JmlAssertionAdder.java:10290)
  	at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExprList(JmlAssertionAdder.java:1408)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitApply(JmlAssertionAdder.java:6427)
  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1394)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitBinary(JmlAssertionAdder.java:9948)
  	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1785)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1394)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1513)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1526)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.addPreConditions(JmlAssertionAdder.java:3722)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertMethodBodyNoInit(JmlAssertionAdder.java:1046)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlMethodDecl(JmlAssertionAdder.java:12570)
  	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1137)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:11458)
  	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1053)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1301)
  	at org.jmlspecs.openjml.JmlCompiler.rac(JmlCompiler.java:573)
  	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:410)
  	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
  	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:652)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
  	at com.sun.tools.javac.main.Main.compile(Main.java:553)
  	at com.sun.tools.javac.main.Main.compile(Main.java:410)
  	at org.jmlspecs.openjml.Main.compile(Main.java:560)
  	at com.sun.tools.javac.main.Main.compile(Main.java:399)
  	at com.sun.tools.javac.main.Main.compile(Main.java:390)
  	at org.jmlspecs.openjml.Main.execute(Main.java:396)
  	at org.jmlspecs.openjml.Main.execute(Main.java:354)
  	at org.jmlspecs.openjml.Main.execute(Main.java:341)
  	at org.jmlspecs.openjml.Main.main(Main.java:313)
Note: openjml.jar(specs18/java/util/Random.jml) uses internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.
1 error
</pre>
</details>

##
```java
public class TestCase {
    public int a = 1;

    //@ requires b >= Math.max(0, -a);
    public void minus(int b) {}
}
```
<details>
  <summary>Compilation Error</summary>
<pre>
Internal JML bug - please report.  BuildOpenJML-0.8.24-20171007
java.lang.AssertionError: _JML__tmp1
	at com.sun.tools.javac.comp.Lower.unbox(Lower.java:3177)
	at com.sun.tools.javac.comp.Lower.boxIfNeeded(Lower.java:3136)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.boxArgs(Lower.java:3112)
	at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3015)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.visitBinary(Lower.java:3367)
	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1785)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.visitAssign(Lower.java:3203)
	at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1686)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitExec(TreeTranslator.java:245)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitTry(TreeTranslator.java:218)
	at com.sun.tools.javac.comp.Lower.visitTry(Lower.java:3897)
	at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1173)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitMethodDef(TreeTranslator.java:145)
	at com.sun.tools.javac.comp.Lower.visitMethodDefInternal(Lower.java:2828)
	at com.sun.tools.javac.comp.Lower.visitMethodDef(Lower.java:2737)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1140)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.visitClassDef(Lower.java:2508)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1056)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2390)
	at com.sun.tools.javac.comp.Lower.translateTopLevelClass(Lower.java:3932)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1522)
	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:420)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:652)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:560)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.execute(Main.java:396)
	at org.jmlspecs.openjml.Main.execute(Main.java:354)
	at org.jmlspecs.openjml.Main.execute(Main.java:341)
	at org.jmlspecs.openjml.Main.main(Main.java:313)
</pre>
</details>

**Comment by davidcok** [comment]
Item (A) has been fixed for the next release (0.8.25)
Items B, C and D were already fixed and will be in the next release.
