### ISSUE TITLE
Internal bug linked to Math.abs?

### ISSUE THREAD

**Issue by ledru** [OpenJML/OpenJML#600]
I have an internal bug when compiling the following program (which performs integer division)

`public class DivisionEntiere {

	//@ requires y != 0;
	//@ ensures Math.abs(\result * y) <= Math.abs(x);
	//@ ensures Math.abs(x) - Math.abs(\result * y) < Math.abs(y);
	//@ ensures \result != 0 ==> ((\result >= 0) <==> (x>= 0 <==> y>=0));
	public static int IntDiv(int x, int y) {
		int z = 0;
		int signe = 1;
		if (x < 0) {
			signe = -1;
			x = -x;
		}
		if (y < 0) {
			signe = -signe;
			y = -y;
		}
		if (y == 0) {
			y=y; // Instruction factice pour voir si elle
				// a été couverte
		}
		// while (x > y) { // Version erronée
			while (x >= y) {
			x = x - y;
			z = z + 1;
		}
		z = signe * z;
		return z;
	}
}
`

The bug disappears if I remove the first two "ensures" (the ones refering to Math.abs).
The bug is present both in Eclipse and in command-line. I can reproduce it under versions 0.8.24 and 0.8.27. But it was not present with 0.8.7

Here is the command line and the error message:

"java" -jar "C:\Users\root\Documents\src\OpenJML\openjml-0.8.27-20180114\openjml.jar"  -rac -nopuritycheck -racCheckAssumptions -racPreconditionEntry -d ..\bin DivisionEntiere.java
Internal JML bug - please report.  BuildOpenJML-0.8.27-20180114
java.lang.AssertionError: The current compile state [ATTR] of class java.lang.Object is previous to FLOW
        at com.sun.tools.javac.util.Assert.error(Assert.java:133)
        at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:991)
        at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:967)
        at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:511)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
        at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1059)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:490)
        at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:1035)
        at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1496)
        at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:425)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
        at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:657)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.main.Main.compile(Main.java:410)
        at org.jmlspecs.openjml.Main.compile(Main.java:567)
        at com.sun.tools.javac.main.Main.compile(Main.java:399)
        at com.sun.tools.javac.main.Main.compile(Main.java:390)
        at org.jmlspecs.openjml.Main.execute(Main.java:403)
        at org.jmlspecs.openjml.Main.execute(Main.java:361)
        at org.jmlspecs.openjml.Main.execute(Main.java:348)
        at org.jmlspecs.openjml.Main.main(Main.java:320)
make: *** [..\bin\DivisionEntiere.class] Erreur 4

**Comment by davidcok** [comment]
Fixed in V0.8.29
