### ISSUE TITLE
Problem with Math.jml

### ISSUE THREAD

**Issue by ledru** [OpenJML/OpenJML#601]
One of my student found the following JML internal bug when using math functions in the java code.
It may be related to issue #600 (problem with Math.Abs) but this time it happens in the code and the error message is different.

Here is the code that causes the error:

`public class Prime {

     public static /*@ pure helper @*/ boolean is_prime(int n) {
        int maxInt = ((Double) Math.ceil(Math.sqrt(n))).intValue();
        for (int i = 0; i <= maxInt; i++) {
            if ((n%i)==0) {
                return false;
            }
        }
        return true;
    }
}
`
I experienced the bug with version 0.8.24 in eclipse.

`[0,00] Executing openjml on Prime.java
C:\EclipseOxygenJML\configuration\org.eclipse.osgi\523\0\.cp\java6\java\lang\Math.jml:329: Note: Runtime assertion checking is not implemented for this type or number of declarations in a quantified expression
      @   ensures (\forall double d; a < d & d < \result; rint(d) != d);
                   ^
Internal JML bug - please report.  BuildOpenJML-20171007
java.lang.AssertionError: _JML__tmp11
	at com.sun.tools.javac.comp.Lower.unbox(Lower.java:3177)
	at com.sun.tools.javac.comp.Lower.boxIfNeeded(Lower.java:3136)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.boxArgs(Lower.java:3090)
	at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3015)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2382)
	at com.sun.tools.javac.comp.Lower.visitVarDef(Lower.java:3547)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
	at org.jmlspecs.openjml.JmlTree$JmlVariableDecl.accept(JmlTree.java:1266)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitTry(TreeTranslator.java:218)
	at com.sun.tools.javac.comp.Lower.visitTry(Lower.java:3897)
	at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1173)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.visitIf(Lower.java:2977)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1269)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitTry(TreeTranslator.java:218)
	at com.sun.tools.javac.comp.Lower.visitTry(Lower.java:3897)
	at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1173)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitTry(TreeTranslator.java:218)
	at com.sun.tools.javac.comp.Lower.visitTry(Lower.java:3897)
	at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1173)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitTry(TreeTranslator.java:218)
	at com.sun.tools.javac.comp.Lower.visitTry(Lower.java:3897)
	at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1173)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitTry(TreeTranslator.java:218)
	at com.sun.tools.javac.comp.Lower.visitTry(Lower.java:3897)
	at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1173)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.Lower.visitBlock(Lower.java:3561)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1209)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.tree.TreeTranslator.visitMethodDef(TreeTranslator.java:145)
	at com.sun.tools.javac.comp.Lower.visitMethodDefInternal(Lower.java:2828)
	at com.sun.tools.javac.comp.Lower.visitMethodDef(Lower.java:2737)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1140)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.visitClassDef(Lower.java:2508)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1056)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
	at com.sun.tools.javac.comp.Lower.translate(Lower.java:2390)
	at com.sun.tools.javac.comp.Lower.translateTopLevelClass(Lower.java:3932)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1522)
	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:420)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:652)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:560)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.executeNS(Main.java:486)
	at org.jmlspecs.openjml.API.execute(API.java:215)
	at org.jmlspecs.openjml.eclipse.OpenJMLInterface.executeExternalCommand(OpenJMLInterface.java:283)
	at org.jmlspecs.openjml.eclipse.Utils$3.run(Utils.java:458)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
ENDING with exit code 4
INTERNAL ERROR: return code = 4   Command: -command=rac -strictJML=false -purityCheck=false -show=false -racShowSource=true -racCheckAssumptions=true -racPreconditionEntry=true -racJavaChecks=false -racCompileToJavaAssert=false -verboseness=1 -checkSpecsPath -nullableByDefault=false -no-internalSpecs -specspath C:/Users/ledru/workspaces/OxygenJML/ZZProblemesEtudiants2/src;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/523/0/.cp/java8;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/523/0/.cp/java7;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/523/0/.cp/java6;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/523/0/.cp/java5;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/523/0/.cp/java4 -sourcepath C:/Users/ledru/workspaces/OxygenJML/ZZProblemesEtudiants2/src -no-internalRuntime -classpath C:/Program Files/Java/jre1.8.0_131/lib/resources.jar;C:/Program Files/Java/jre1.8.0_131/lib/rt.jar;C:/Program Files/Java/jre1.8.0_131/lib/jsse.jar;C:/Program Files/Java/jre1.8.0_131/lib/jce.jar;C:/Program Files/Java/jre1.8.0_131/lib/charsets.jar;C:/Program Files/Java/jre1.8.0_131/lib/jfr.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/access-bridge-64.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/cldrdata.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/dnsns.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/jaccess.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/jfxrt.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/localedata.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/nashorn.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/sunec.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/sunjce_provider.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/sunmscapi.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/sunpkcs11.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/zipfs.jar;C:/EclipseOxygenJML/plugins/org.junit_4.12.0.v201504281640/junit.jar;C:/EclipseOxygenJML/plugins/org.hamcrest.core_1.3.0.v201303031735.jar;C:/Users/ledru/workspaces/OxygenJML/ZZProblemesEtudiants2/src;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/522/0/.cp/jmlruntime.jar;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/522/0/.cp/jmlruntime.jar -d C:/Users/ledru/workspaces/OxygenJML/ZZProblemesEtudiants2/bin C:/Users/ledru/workspaces/OxygenJML/ZZProblemesEtudiants2/src/Prime.java 
`

**Comment by davidcok** [comment]
This problem has been fixed along the way. It proves OK using OpenJML21, and is in the test suite.
