### ISSUE TITLE
tried to access field com.sun.tools.javac.main.Main.out from class org.jmlspecs.openjml.Main

### ISSUE THREAD

**Issue by sgonschorowski** [OpenJML/OpenJML#619]
Hello,

i get a java.lang.IllegalAccessError when i try to execute the following code:
```
import org.jmlspecs.openjml.Factory;
import org.jmlspecs.openjml.IAPI;


class app {

    public static void main(String[] argv) {
        try {
            IAPI m = Factory.makeAPI(new String[0]);
            String s = m.version();
            System.out.println(s);
        } catch (Exception var3) {
            System.out.println(var3);
        }

    }
}
```

the complete error message look like this:

```
Exception in thread "main" java.lang.IllegalAccessError: tried to access field com.sun.tools.javac.main.Main.out from class org.jmlspecs.openjml.Main
	at org.jmlspecs.openjml.Main.initialize(Main.java:269)
	at org.jmlspecs.openjml.Main.<init>(Main.java:260)
	at org.jmlspecs.openjml.API.<init>(API.java:132)
	at org.jmlspecs.openjml.Factory$APIFactory.makeAPI(Factory.java:34)
	at org.jmlspecs.openjml.Factory.makeAPI(Factory.java:45)
	at app.main(app.java:6)

```

isn't it the normal way to get a new API instance?

**Comment by sgonschorowski** [comment]
It was up to IntelliJ IDEA because there are used diffrent classloaders. I tryed to start it from terminal and it runs fine.
