### ISSUE TITLE
OpenJML crash after emitting type error

### ISSUE THREAD

**Issue by RustanLeino** [OpenJML/OpenJML#636]
The following program has a type error. OpenJML reports it and then crashes.

    import java.nio.charset.StandardCharsets;
    public class A {
        //@ public normal_behavior
        //@   requires new String(s, cs) != null;
        public void m(String s, StandardCharsets cs) {
        }
    }

Here is the output:

```
A.java:7: error: no suitable constructor found for String(String,StandardCharsets)
    //@   requires new String(s, cs) != null;
                   ^
    constructor String.String(byte[],int) is not applicable
      (argument mismatch; String cannot be converted to byte[])
    constructor String.String(byte[],String) is not applicable
      (argument mismatch; String cannot be converted to byte[])
    constructor String.String(byte[],Charset) is not applicable
      (argument mismatch; String cannot be converted to byte[])
    constructor String.String(char[],boolean) is not applicable
      (argument mismatch; String cannot be converted to char[])
Internal JML bug - please report.  Build(version info not available)
java.lang.NullPointerException
	at org.jmlspecs.openjml.Utils.isJMLStatic(Utils.java:345)
	at org.jmlspecs.openjml.Utils.parents(Utils.java:737)
	at com.sun.tools.javac.comp.JmlAttr.isPureMethod(JmlAttr.java:5412)
	at com.sun.tools.javac.comp.JmlAttr.visitNewClass(JmlAttr.java:896)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1516)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:625)
	at com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:3066)
	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1785)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:618)
	at com.sun.tools.javac.comp.JmlAttr.attribExpr(JmlAttr.java:6140)
	at com.sun.tools.javac.comp.JmlAttr.visitJmlMethodClauseExpr(JmlAttr.java:2907)
	at org.jmlspecs.openjml.JmlTree$JmlMethodClauseExpr.accept(JmlTree.java:2059)
	at com.sun.tools.javac.comp.JmlAttr.visitJmlSpecificationCase(JmlAttr.java:3097)
	at org.jmlspecs.openjml.JmlTree$JmlSpecificationCase.accept(JmlTree.java:2544)
	at com.sun.tools.javac.comp.JmlAttr.visitJmlMethodSpecs(JmlAttr.java:3158)
	at org.jmlspecs.openjml.JmlTree$JmlMethodSpecs.accept(JmlTree.java:2264)
	at com.sun.tools.javac.comp.JmlAttr.visitBlock(JmlAttr.java:654)
	at com.sun.tools.javac.comp.JmlAttr.visitJmlBlock(JmlAttr.java:3979)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1225)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at com.sun.tools.javac.comp.JmlAttr.attribStat(JmlAttr.java:509)
	at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1013)
	at com.sun.tools.javac.comp.JmlAttr.visitMethodDef(JmlAttr.java:1007)
	at com.sun.tools.javac.comp.JmlAttr.visitJmlMethodDecl(JmlAttr.java:6021)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1156)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at com.sun.tools.javac.comp.JmlAttr.attribStat(JmlAttr.java:509)
	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4376)
	at com.sun.tools.javac.comp.JmlAttr.attribClassBody(JmlAttr.java:492)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4284)
	at com.sun.tools.javac.comp.JmlAttr.attribClass(JmlAttr.java:370)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4213)
	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4188)
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1258)
	at org.jmlspecs.openjml.JmlCompiler.attribute(JmlCompiler.java:480)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:703)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:577)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.execute(Main.java:413)
	at org.jmlspecs.openjml.Main.execute(Main.java:371)
	at org.jmlspecs.openjml.Main.execute(Main.java:358)
	at org.jmlspecs.openjml.Main.main(Main.java:330)

```

  Rustan

**Comment by davidcok** [comment]
Fixed on the development branch. A case of type attribution (JmlAttr) getting an ErrorType when checking the new String(...) expression, but then some later code presumed a successful, non-error type as the result.
