### ISSUE TITLE
Failed to compile RAC

### ISSUE THREAD

**Issue by snowball77** [OpenJML/OpenJML#645]
When compiling my project with RAC, I get an internal error. In case you would like to reproduce it, the code is available at https://git.rss.iste.uni-stuttgart.de/open-to-public/pse/tree/master/code and I tried to instrument the main project.

----

java -jar ~/Downloads/openjml-0.8.39-20180701/openjml.jar -rac -d ../target/classes  -dirs main/java -cp ../../de.unistuttgart.iste.rss.oo.hamstersimulator.core/target/core-0.0.1-SNAPSHOT.jar:../../de.unistuttgart.iste.rss.utils/target/utils-0.0.1-SNAPSHOT.jar:../../de.unistuttgart.iste.rss.oo.hamstersimulator.ui/target/ui-0.0.1-SNAPSHOT.jar -internalSpecs=false
Internal JML bug - please report.  BuildOpenJML-0.8.39-20180701
java.lang.NullPointerException
	at com.sun.tools.javac.code.Types.makeFunctionalInterfaceClass(Types.java:635)
	at com.sun.tools.javac.comp.LambdaToMethod$LambdaAnalyzerPreprocessor$TranslationContext.<init>(LambdaToMethod.java:1775)
	at com.sun.tools.javac.comp.LambdaToMethod$LambdaAnalyzerPreprocessor$LambdaTranslationContext.<init>(LambdaToMethod.java:1859)
	at com.sun.tools.javac.comp.LambdaToMethod$LambdaAnalyzerPreprocessor.analyzeLambda(LambdaToMethod.java:1343)
	at com.sun.tools.javac.comp.LambdaToMethod$LambdaAnalyzerPreprocessor.visitLambda(LambdaToMethod.java:1328)
	at com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1624)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitApply(TreeTranslator.java:275)
	at com.sun.tools.javac.comp.LambdaToMethod$LambdaAnalyzerPreprocessor.visitApply(LambdaToMethod.java:1214)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.visitExec(TreeTranslator.java:245)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.LambdaToMethod$LambdaAnalyzerPreprocessor.visitBlock(LambdaToMethod.java:1237)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1227)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.visitTry(TreeTranslator.java:218)
	at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1173)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:162)
	at com.sun.tools.javac.comp.LambdaToMethod$LambdaAnalyzerPreprocessor.visitBlock(LambdaToMethod.java:1237)

**Comment by snowball77** [comment]
I found this line of code to be responsible:
        final Tile currentTile = this.internalHamster.getCurrentTile().get(); //orElseThrow(() -> new IllegalArgumentException());

If I exchange the get() by the commented part, the RAC compiler fails...

**Comment by davidcok** [comment]
Steven - I've started to look at this. Are you using the release version or some branch from GitHub?

**Comment by davidcok** [comment]
This problem is too old to now try to reproduce. I note that it used OpenJML 8, which would not have had support for lambda functions. Closing without fixing. Sorry.
