### ISSUE TITLE
Internal errors due to asserted implications

### ISSUE THREAD

**Issue by benozol** [OpenJML/OpenJML#684]
Implications in assertions can trigger internal bugs in a number of circumstances, for example:
```jml
import java.util.Collection;
public class Test {
    void m(boolean a, boolean b, Collection<Object> c) {
        //@ assert (a && b ==> c == null); // fails
        //@ assert (a && b ==> this == null); // works

        //@ assert (a  && b ==> !c.isEmpty()); // fails
        //@ assert (a  ==> !c.isEmpty()); // works

        //@ assert ((a && b && !c.isEmpty()) ==> !c.isEmpty()); // fails
        //@ assert ((a && b && !c.isEmpty()) ==> 0 < c.size()); // works
    }
}
```
There are of course easy workarounds, for example replacing `A ==> B` by `!A || B` but at the expense of readability.

Here is a typical backtrace:
```
Internal JML bug - please report.  BuildOpenJML-development-20190613
java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.util.Assert.check(Assert.java:45)
	at com.sun.tools.javac.util.Bits.isMember(Bits.java:231)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.checkInit(Flow.java:1602)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.checkInit(Flow.java:1596)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitIdent(Flow.java:2416)
	at com.sun.tools.javac.comp.JmlFlow$JmlAssignAnalyzer.visitIdent(JmlFlow.java:639)
	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:406)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExpr(Flow.java:1644)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitBinary(Flow.java:2409)
	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1785)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:406)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1)
	at com.sun.tools.javac.comp.JmlFlow$JmlAssignAnalyzer.visitJmlBinary(JmlFlow.java:488)
	at org.jmlspecs.openjml.JmlTree$JmlBinary.accept(JmlTree.java:1498)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:406)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1)
	at com.sun.tools.javac.tree.TreeScanner.visitParens(TreeScanner.java:226)
	at com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1661)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:406)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExpr(Flow.java:1644)
	at com.sun.tools.javac.comp.JmlFlow$JmlAssignAnalyzer.visitJmlStatementExpr(JmlFlow.java:585)
	at org.jmlspecs.openjml.JmlTree$JmlStatementExpr.accept(JmlTree.java:2996)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:406)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
	at com.sun.tools.javac.comp.JmlFlow$JmlAssignAnalyzer.visitJmlBlock(JmlFlow.java:499)
	at org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1315)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:406)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:1823)
	at com.sun.tools.javac.comp.JmlFlow$JmlAssignAnalyzer.visitJmlMethodDecl(JmlFlow.java:477)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1243)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:406)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:1758)
	at com.sun.tools.javac.comp.JmlFlow$JmlAssignAnalyzer.visitJmlClassDecl(JmlFlow.java:510)
	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1156)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:406)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:2458)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:2441)
	at com.sun.tools.javac.comp.JmlFlow.analyzeTree(JmlFlow.java:1202)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1337)
	at org.jmlspecs.openjml.JmlCompiler.flow(JmlCompiler.java:545)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:734)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:577)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.execute(Main.java:413)
	at org.jmlspecs.openjml.Main.execute(Main.java:371)
	at org.jmlspecs.openjml.Main.execute(Main.java:358)
	at org.jmlspecs.openjml.Main.main(Main.java:330)
```

**Comment by davidcok** [comment]
Fixed and merged to development. A problem with Flow checks for initialization.
