### ISSUE TITLE
Wildcard in loop_modifies triggers internal error in ESC

### ISSUE THREAD

**Issue by benozol** [OpenJML/OpenJML#686]
Example:

```java
public class Test {
	void f1(Queue<Integer> q) {
		//@ loop_modifies q.content.*; // fails
		// loop_modifies q.content.size; // works
		while (!q.isEmpty())
			q.poll();
	}
}
```

```
$ java -jar ~/setups/openjml/openjml.jar -esc -cp . Test.java
error: An internal JML error occurred, possibly recoverable.  Please report the bug with as much information as you can.
  Reason: Internal exception: class java.lang.NullPointerException
  java.lang.NullPointerException
  	at org.jmlspecs.openjml.JmlSpecs.getSpecs(JmlSpecs.java:1221)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.havocModelFields(JmlAssertionAdder.java:10532)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.havocModelFields(JmlAssertionAdder.java:10527)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.loopHelperHavoc(JmlAssertionAdder.java:13686)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.loopHelperHavoc(JmlAssertionAdder.java:13713)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlWhileLoop(JmlAssertionAdder.java:16693)
  	at org.jmlspecs.openjml.JmlTree$JmlWhileLoop.accept(JmlTree.java:1818)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1339)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convertMethodBodyNoInit(JmlAssertionAdder.java:1106)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlMethodDecl(JmlAssertionAdder.java:14292)
  	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1210)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:13075)
  	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1123)
  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  	at org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1339)
  	at org.jmlspecs.openjml.esc.JmlEsc.check(JmlEsc.java:113)
  	at org.jmlspecs.openjml.JmlCompiler.esc(JmlCompiler.java:702)
  	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:445)
  	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
  	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:733)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
  	at com.sun.tools.javac.main.Main.compile(Main.java:553)
  	at com.sun.tools.javac.main.Main.compile(Main.java:410)
  	at org.jmlspecs.openjml.Main.compile(Main.java:577)
  	at com.sun.tools.javac.main.Main.compile(Main.java:399)
  	at com.sun.tools.javac.main.Main.compile(Main.java:390)
  	at org.jmlspecs.openjml.Main.execute(Main.java:413)
  	at org.jmlspecs.openjml.Main.execute(Main.java:371)
  	at org.jmlspecs.openjml.Main.execute(Main.java:358)
  	at org.jmlspecs.openjml.Main.main(Main.java:330)
error: ESC could not be attempted because of a failure in typechecking or AST transformation: f1
2 errors
```

**Comment by davidcok** [comment]
Fixed and pushed to development; also needs the development branch of 'Specs':
1) Fixed the crash
2) Added some checks for incorrect assigns statements with more to come
3) The correct specification of the loop is

import java.util.Queue;
public class Test {
    void f1(Queue<Integer> q) {
        //@ loop_modifies q.content;
        //@ loop_invariant \invariant_for(q);
        while (!q.isEmpty())
            q.poll();
    }
}

Possibly we could implicitly add the invariant on q when methods of q are being called.

**Comment by davidcok** [comment]
With updates to library specs, this is now specified as

import java.util.Queue;
public class Test {
    void f1(Queue<Integer> q) {
        //@ loop_modifies q.values;
        //@ loop_invariant \invariant_for(q);
        while (!q.isEmpty())
            q.poll();
    }
}

This example is in the test suite (gitbug688). Closing this issue
