### ISSUE TITLE
Cannot run the jar from the release

### ISSUE THREAD

**Issue by bobismijnnaam** [OpenJML/OpenJML#693]
When I try to run the jar from the github release, I get the following error:

```
$ java -jar ./openjml.jar -help
Exception in thread "main" java.lang.NoSuchFieldError: out
	at org.jmlspecs.openjml.Main.initialize(Main.java:290)
	at org.jmlspecs.openjml.Main.<init>(Main.java:281)
	at org.jmlspecs.openjml.Main.execute(Main.java:411)
	at org.jmlspecs.openjml.Main.execute(Main.java:372)
	at org.jmlspecs.openjml.Main.execute(Main.java:359)
	at org.jmlspecs.openjml.Main.main(Main.java:331)
```

I've tried 0.8.43 and 0.8.42. I have the following java version:

```
$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

I have never had this error with other jar files so I'm assuming my java installation is not corrupted, but I can dig into this if needed. I can also try to compile it myself but that will take a while.

**Comment by davidcok** [comment]
OpenJML requires Java 8.

- David

**Comment by bobismijnnaam** [comment]
Ah, I feel stupid now. Apologies for the fuss.
