### ISSUE TITLE
Internal error when testing example code

### ISSUE THREAD

**Issue by lucashoeft** [OpenJML/OpenJML#696]
Java version (`$ java -version`):
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

The AddLoop.java file (code is from the online openJML editor) and the folder which contains the .jar file are in the same folder.

After executing `$ java -jar openjml/openjml.jar -esc AddLoop.java`, I get following output in the terminal:

```
warning: An internal JML error occurred, possibly recoverable.  Please report the bug with as much information as you can.
  Reason: Last resort loading of extensions
warning: An internal JML error occurred, possibly recoverable.  Please report the bug with as much information as you can.
  Reason: Last resort loading of extensions
AddLoop.java:3: error: Unknown backslash identifier: \result
    //@ ensures \result == x + y;
                ^
openjml/openjml.jar(specs/java/lang/Object.jml):55: error: Unknown backslash identifier: \result
      @   ensures \result == \erasure(\typeof(this));
                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):66: error: Unknown backslash identifier: \result
    //@     ensures \result == System.identityHashCode(this);
                    ^
openjml/openjml.jar(specs/java/lang/Object.jml):74: error: The type or expression near here is invalid (or not implemented): ( token (*...*) in JmlParser.term3())
      @     ensures (* \result is true when obj is "equal to" this object *);
                    ^
openjml/openjml.jar(specs/java/lang/Object.jml):74: error: illegal start of expression
      @     ensures (* \result is true when obj is "equal to" this object *);
                                                                            ^
openjml/openjml.jar(specs/java/lang/Object.jml):78: error: Unknown backslash identifier: \result
      @     ensures \result;
                    ^
openjml/openjml.jar(specs/java/lang/Object.jml):81: error: Unknown backslash identifier: \type
      @     requires obj != null && \typeof(this) == \type(Object);
                                                     ^
openjml/openjml.jar(specs/java/lang/Object.jml):82: error: Unknown backslash identifier: \result
      @     ensures \result <==> this == obj;
                    ^
openjml/openjml.jar(specs/java/lang/Object.jml):86: error: Unknown backslash identifier: \result
      @     ensures !\result;
                     ^
openjml/openjml.jar(specs/java/lang/Object.jml):94: error: Unknown backslash identifier: \result
      @   ensures \elemtype(\typeof(\result)) == \elemtype(\typeof(this));
                                    ^
openjml/openjml.jar(specs/java/lang/Object.jml):94: error: The expression is invalid or not terminated by a semicolon
      @   ensures \elemtype(\typeof(\result)) == \elemtype(\typeof(this));
                                           ^
openjml/openjml.jar(specs/java/lang/Object.jml):98: error: Unknown backslash identifier: \fresh
    //-RAC@    ensures \fresh(\result) && \result != this; // Assuming this is true for arrays
                       ^
openjml/openjml.jar(specs/java/lang/Object.jml):106: error: Unknown backslash identifier: \result
      @   ensures \typeof(\result) == \typeof(this);  // This is not a strict requirement, although generally expected
                          ^
openjml/openjml.jar(specs/java/lang/Object.jml):107: error: Unknown backslash identifier: \result
      @   ensures \result != this; // This is not a strict requirement, although generally expected
                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):118: error: Unknown backslash identifier: \result
      @   ensures \result instanceof Object[];
                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):119: error: Unknown backslash identifier: \result
      @   ensures ((Object[])\result).length == ((Object[])this).length;
                             ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: Unknown backslash identifier: \forall
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                        ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                 ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                        ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                         ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                          ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                           ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                               ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                                ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                                       ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                                         ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                                                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):120: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((Object[])this).length; ((Object[])this)[i] == ((Object[])\result)[i]);
                                                                                    ^
openjml/openjml.jar(specs/java/lang/Object.jml):121: error: illegal start of expression
      @ also public behavior
        ^
openjml/openjml.jar(specs/java/lang/Object.jml):124: error: Unknown backslash identifier: \result
      @   ensures \result instanceof int[];
                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):125: error: Unknown backslash identifier: \result
      @   ensures ((int[])\result).length == ((int[])this).length;
                          ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: Unknown backslash identifier: \forall
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                        ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                 ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                     ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                      ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                       ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                        ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                            ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                             ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                    ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                      ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                             ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                              ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: illegal start of expression
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                                            ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                                                 ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: Unknown backslash identifier: \result
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                                                         ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                                                            ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                                                             ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                                                              ^
openjml/openjml.jar(specs/java/lang/Object.jml):126: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((int[])this).length; ((int[])this)[i] == ((int[])\result)[i]);
                                                                                                               ^
openjml/openjml.jar(specs/java/lang/Object.jml):130: error: Unknown backslash identifier: \result
      @   ensures \result instanceof long[];
                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):131: error: Unknown backslash identifier: \result
      @   ensures ((long[])\result).length == ((long[])this).length;
                           ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: Unknown backslash identifier: \forall
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                        ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                 ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                      ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                       ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                        ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                         ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                             ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                              ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                     ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                       ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                               ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: illegal start of expression
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                              ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                                    ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: Unknown backslash identifier: \result
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                                     ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                                            ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                                               ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                                                ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                                                 ^
openjml/openjml.jar(specs/java/lang/Object.jml):132: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((long[])this).length; ((long[])this)[i] == ((long[])\result)[i]);
                                                                                                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):136: error: Unknown backslash identifier: \result
      @   ensures \result instanceof short[];
                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):137: error: Unknown backslash identifier: \result
      @   ensures ((short[])\result).length == ((short[])this).length;
                            ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: Unknown backslash identifier: \forall
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                   ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                        ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                                ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                                 ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                                  ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: illegal start of type
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                                       ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: <identifier> expected
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                                        ^
openjml/openjml.jar(specs/java/lang/Object.jml):138: error: ';' expected
      @   ensures (\forall int i; 0 <= i && i < ((short[])this).length; ((short[])this)[i] == ((short[])\result)[i]);
                                                         ^
Internal JML bug - please report.  BuildOpenJML-0.8.46-20200505
java.lang.NullPointerException
	at com.sun.tools.javac.parser.JmlParser.parseTypeSpecs(JmlParser.java:2082)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceBodyDeclaration(JmlParser.java:1216)
	at com.sun.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3563)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceBody(JmlParser.java:420)
	at com.sun.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3412)
	at com.sun.tools.javac.parser.JmlParser.classDeclaration(JmlParser.java:431)
	at com.sun.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3353)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceOrEnumDeclaration(JmlParser.java:285)
	at com.sun.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:3342)
	at com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:3282)
	at com.sun.tools.javac.parser.JmlParser.parseCompilationUnit(JmlParser.java:170)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:633)
	at com.sun.tools.javac.main.JmlCompiler.parse(JmlCompiler.java:143)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:670)
	at com.sun.tools.javac.main.JmlCompiler.parseSingleFile(JmlCompiler.java:251)
	at com.sun.tools.javac.main.JmlCompiler.parseSpecs(JmlCompiler.java:223)
	at com.sun.tools.javac.main.JmlCompiler.completeBinaryEnterTodo(JmlCompiler.java:359)
	at com.sun.tools.javac.main.JmlCompiler.loadSpecsForBinary(JmlCompiler.java:337)
	at com.sun.tools.javac.comp.JmlResolve.loadClass(JmlResolve.java:183)
	at com.sun.tools.javac.comp.Resolve.findGlobalType(Resolve.java:2015)
	at com.sun.tools.javac.comp.Resolve.findType(Resolve.java:2097)
	at com.sun.tools.javac.comp.Resolve.findIdent(Resolve.java:2126)
	at com.sun.tools.javac.comp.Resolve.resolveIdent(Resolve.java:2400)
	at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3183)
	at com.sun.tools.javac.comp.JmlAttr.visitIdent(JmlAttr.java:4635)
	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:577)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:639)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:632)
	at com.sun.tools.javac.comp.JmlAttr.attribType(JmlAttr.java:2514)
	at com.sun.tools.javac.comp.MemberEnter.signature(MemberEnter.java:405)
	at com.sun.tools.javac.comp.MemberEnter.visitMethodDef(MemberEnter.java:592)
	at com.sun.tools.javac.comp.JmlMemberEnter.visitMethodDef(JmlMemberEnter.java:1717)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
	at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1263)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:438)
	at com.sun.tools.javac.comp.JmlMemberEnter.memberEnter(JmlMemberEnter.java:175)
	at com.sun.tools.javac.comp.JmlMemberEnter.finishClass(JmlMemberEnter.java:321)
	at com.sun.tools.javac.comp.MemberEnter.finish(MemberEnter.java:1446)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1241)
	at com.sun.tools.javac.comp.JmlMemberEnter.complete(JmlMemberEnter.java:1865)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.flags(Symbol.java:973)
	at com.sun.tools.javac.comp.JmlAttr.attribClassBody(JmlAttr.java:515)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4287)
	at com.sun.tools.javac.comp.JmlAttr.attribClass(JmlAttr.java:414)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4236)
	at com.sun.tools.javac.comp.JmlAttr.attribClass(JmlAttr.java:414)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4216)
	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4191)
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1258)
	at com.sun.tools.javac.main.JmlCompiler.attribute(JmlCompiler.java:479)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at com.sun.tools.javac.main.JmlCompiler.compile2(JmlCompiler.java:712)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:581)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.execute(Main.java:417)
	at org.jmlspecs.openjml.Main.execute(Main.java:375)
	at org.jmlspecs.openjml.Main.execute(Main.java:362)
	at org.jmlspecs.openjml.Main.main(Main.java:334)
```

The java file:

```java
public class AddLoop {
    //@ requires true;
    //@ ensures \result == x + y;
    public static int AddLoop(int x, int y) {
        int sum = x;
        if (y > 0) {
            int n = y;

            //@ maintaining sum == x + y - n && 0 <= n;
            //@ decreases n;
            while (n > 0) {
                sum = sum + 1;
                n = n - 1;
            }
        } else {
            int n = -y;

            //@ maintaining sum == x + y + n && 0 <= n;
            //@ decreases n;
            while (n > 0) {
                sum = sum - 1;

                n = n - 1;
            }
        }
        return sum;

    }
}
```

**Comment by davidcok** [comment]
For sure something went wrong with the parsing here. You don't indicate which version of openjml you are using.
In any case, the current version (0.8.50) only shows some overflow errors. 
[Sorry for the delayed response.]

**Comment by Backslash1** [comment]
@davidcok @lucashoeft what did you try to fix this? I am using Java 1.8 and openjml0.8.51.

**Comment by davidcok** [comment]
The openjml.8 series is obsolete. You should be using the 17 series and Java 17

**Comment by Backslash1** [comment]
Thanks for the input, surprisingly it worked on Linux with the same specifications.
