### ISSUE TITLE
Boogie does not work out of the box?

### ISSUE THREAD

**Issue by saraswat** [OpenJML/OpenJML#727]
Try a vacuous program (same problem with real programs):
```
public class HW{
    HW(){}
}
```

This works just fine without `-boogie`:
```
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -jar ~/Downloads/openjml/openjml.jar  -cp .  -esc -exec ~/Downloads/stainless-scalac-standalone-0/z3/z3 -progress HW.java
Proving methods in HW
Starting proof of HW.HW() with prover z3_4_3
Method assertions are validated [1.07 secs]
HW.java:10: Feasibility check #1 - end of preconditions : OK [0.00 secs]
HW.java:10: Feasibility check #2 - at program exit : OK [0.00 secs]
Completed proof of HW.HW() with prover z3_4_3 - no warnings [1.15 secs]
Completed proving methods in HW [1.16 secs]
Note: Summary:
    Valid:        1
    Invalid:      0
    Infeasible:   0
    Timeout:      0
    Error:        0
    Skipped:      0
   TOTAL METHODS: 1
   Classes:       1 proved of 1
   Model Classes: 0
   Model methods: 0 proved of 0
   DURATION:          1.3 secs
bash-3.2$ 
```
However, with `-boogie` one gets dreaded NPEs:
```
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -jar ~/Downloads/openjml/openjml.jar  -cp .  -esc -exec ~/Downloads/stainless-scalac-standalone-0/z3/z3 -progress -boogie HW.java
Proving methods in HW
Starting proof of HW.HW() with prover z3_4_3
SKIPPING PROOF OF <init>
java.lang.NullPointerException
        at org.jmlspecs.openjml.esc.JmlEsc.doMethod(JmlEsc.java:344)
        at org.jmlspecs.openjml.esc.JmlEsc.visitMethodDef(JmlEsc.java:216)
        at org.jmlspecs.openjml.vistors.JmlTreeScanner.visitJmlMethodDecl(JmlTreeScanner.java:242)
        at org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1267)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at org.jmlspecs.openjml.vistors.JmlTreeScanner.scan(JmlTreeScanner.java:67)
        at org.jmlspecs.openjml.esc.JmlEsc.visitClassDef(JmlEsc.java:164)
        at org.jmlspecs.openjml.vistors.JmlTreeScanner.visitJmlClassDecl(JmlTreeScanner.java:116)
        at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1179)
        at org.jmlspecs.openjml.esc.JmlEsc.check(JmlEsc.java:116)
        at com.sun.tools.javac.main.JmlCompiler.esc(JmlCompiler.java:696)
        at com.sun.tools.javac.main.JmlCompiler.desugar(JmlCompiler.java:454)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
        at com.sun.tools.javac.main.JmlCompiler.compile2(JmlCompiler.java:727)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.main.Main.compile(Main.java:410)
        at org.jmlspecs.openjml.Main.compile(Main.java:581)
        at com.sun.tools.javac.main.Main.compile(Main.java:399)
        at com.sun.tools.javac.main.Main.compile(Main.java:390)
        at org.jmlspecs.openjml.Main.execute(Main.java:417)
        at org.jmlspecs.openjml.Main.execute(Main.java:375)
        at org.jmlspecs.openjml.Main.execute(Main.java:362)
        at org.jmlspecs.openjml.Main.main(Main.java:334)
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Prover aborted with exception: java.lang.NullPointerException
Proof ABORTED of HW.HW() with prover z3_4_3 - exception
Completed proving methods in HW [0.02 secs]
Note: Summary:
    Valid:        0
    Invalid:      0
    Infeasible:   0
    Timeout:      0
    Error:        1
    Skipped:      0
   TOTAL METHODS: 1
   Classes:       0 proved of 1
   Model Classes: 0
   Model methods: 0 proved of 0
   DURATION:          0.1 secs
1 error
bash-3.2$ 
```

Boogie version:
```
boogie -version
Boogie program verifier version 2.8.29.0, Copyright (c) 2003-2014, Microsoft.
bash-3.2$ 
```

Am I doing something wrong (e.g. in installing boogie) or does `-boogie` really not work?

**Comment by davidcok** [comment]
I should remove the -boogie option. It was aspirational but never implemented.
