### ISSUE TITLE
Crash with a new-object call in a specification

### ISSUE THREAD

**Issue by davidcok** [OpenJML/OpenJML#751]
This crash goes away wench new Double is replace by Double.valueOf
but (a) it should not crash
(b) there should be an error if a constructor call is used in a spec

leavens@NEW-SURFACE:~/temp$ java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-Ubuntu-118.04)
OpenJDK 64-Bit Server VM (build 17+35-Ubuntu-118.04, mixed mode, sharing)
leavens@NEW-SURFACE:~/temp$ esc -version
openjml 0.16.0-alpha-5

/usr/local/openjml/specs/java/lang/StrictMath.jml:640: warning: [removal] Double(double) in Double has been deprecated and marked for removal
     @      requires new Double(a).compareTo(new Double(b)) == 0;
                                             ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:640: warning: [removal] Double(double) in Double has been deprecated and marked for removal
     @      requires new Double(a).compareTo(new Double(b)) == 0;
                     ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:643: warning: [removal] Double(double) in Double has been deprecated and marked for removal
     @      requires new Double(a).compareTo(new Double(b)) <= 0;
                                             ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:643: warning: [removal] Double(double) in Double has been deprecated and marked for removal
     @      requires new Double(a).compareTo(new Double(b)) <= 0;
                     ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:646: warning: [removal] Double(double) in Double has been deprecated and marked for removal
     @      requires new Double(a).compareTo(new Double(b)) >= 0;
                                             ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:646: warning: [removal] Double(double) in Double has been deprecated and marked for removal
     @      requires new Double(a).compareTo(new Double(b)) >= 0;
                     ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:616: warning: [removal] Float(float) in Float has been deprecated and marked for removal
     @     requires new Float(a).compareTo(new Float(b)) == 0;
                                           ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:616: warning: [removal] Float(float) in Float has been deprecated and marked for removal
     @     requires new Float(a).compareTo(new Float(b)) == 0;
                    ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:619: warning: [removal] Float(float) in Float has been deprecated and marked for removal
     @     requires new Float(a).compareTo(new Float(b)) <= 0;
                                           ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:619: warning: [removal] Float(float) in Float has been deprecated and marked for removal
     @     requires new Float(a).compareTo(new Float(b)) <= 0;
                    ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:622: warning: [removal] Float(float) in Float has been deprecated and marked for removal
     @     requires new Float(a).compareTo(new Float(b)) >= 0;
                                           ^
/usr/local/openjml/specs/java/lang/StrictMath.jml:622: warning: [removal] Float(float) in Float has been deprecated and marked for removal
     @     requires new Float(a).compareTo(new Float(b)) >= 0;
                    ^
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
 Reason: No logical function for method <init>
java.lang.NullPointerException: Cannot read field "type" because "expr" is null
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.addImplicitConversion(JmlAssertionAdder.java:11038)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertArgs(JmlAssertionAdder.java:7905)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.applyHelper(JmlAssertionAdder.java:8284)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitApply(JmlAssertionAdder.java:7791)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1752)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1484)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitBinary(JmlAssertionAdder.java:12262)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2111)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1484)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertNoSplit(JmlAssertionAdder.java:1691)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.addMethodAxioms(JmlAssertionAdder.java:18928)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.addMethodAxiomsPlus(JmlAssertionAdder.java:10311)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.applyHelper(JmlAssertionAdder.java:8443)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitApply(JmlAssertionAdder.java:7791)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1752)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1484)
	at jdk.compiler/org.jmlspecs.openjml.ext.Arithmetic.makeBinaryOp(Arithmetic.java:297)
	at jdk.compiler/org.jmlspecs.openjml.ext.Arithmetic$Math.rewriteBinary(Arithmetic.java:678)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitBinary(JmlAssertionAdder.java:12255)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2111)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1484)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1627)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1644)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.addPreConditions(JmlAssertionAdder.java:4198)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertMethodBodyNoInit(JmlAssertionAdder.java:1100)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlMethodDecl(JmlAssertionAdder.java:15659)
	at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1339)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:14249)
	at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1251)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1394)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlEsc.check(JmlEsc.java:112)
	at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.esc(JmlCompiler.java:457)
	at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.desugar(JmlCompiler.java:209)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:321)
	at jdk.compiler/org.jmlspecs.openjml.Main.compile(Main.java:532)
	at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:372)
	at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:330)
	at jdk.compiler/org.jmlspecs.openjml.Main.main(Main.java:293)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:53)
java.lang.NullPointerException: Cannot read field "type" because "expr" is null
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.addImplicitConversion(JmlAssertionAdder.java:11038)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertArgs(JmlAssertionAdder.java:7905)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.applyHelper(JmlAssertionAdder.java:8284)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitApply(JmlAssertionAdder.java:7791)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1752)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1484)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitBinary(JmlAssertionAdder.java:12262)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2111)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1484)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertNoSplit(JmlAssertionAdder.java:1691)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.addMethodAxioms(JmlAssertionAdder.java:18928)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.addMethodAxiomsPlus(JmlAssertionAdder.java:10311)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.applyHelper(JmlAssertionAdder.java:8443)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitApply(JmlAssertionAdder.java:7791)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1752)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1484)
	at jdk.compiler/org.jmlspecs.openjml.ext.Arithmetic.makeBinaryOp(Arithmetic.java:297)
	at jdk.compiler/org.jmlspecs.openjml.ext.Arithmetic$Math.rewriteBinary(Arithmetic.java:678)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitBinary(JmlAssertionAdder.java:12255)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2111)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1484)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1627)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertJML(JmlAssertionAdder.java:1644)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.addPreConditions(JmlAssertionAdder.java:4198)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertMethodBodyNoInit(JmlAssertionAdder.java:1100)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlMethodDecl(JmlAssertionAdder.java:15659)
	at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1339)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:14249)
	at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1251)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1394)
	at jdk.compiler/org.jmlspecs.openjml.esc.JmlEsc.check(JmlEsc.java:112)
	at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.esc(JmlCompiler.java:457)
	at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.desugar(JmlCompiler.java:209)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:321)
	at jdk.compiler/org.jmlspecs.openjml.Main.compile(Main.java:532)
	at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:372)
	at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:330)
	at jdk.compiler/org.jmlspecs.openjml.Main.main(Main.java:293)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:53)
1 error
12 warnings

        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        Leavens@ucf.edu

-----Original Message-----
From: David Cok <david.r.cok@gmail.com> 
Sent: Tuesday, October 19, 2021 12:15 PM
To: Gary Leavens <Leavens@ucf.edu>
Subject: build

Gary, I generated and published a new release that has a build for Ubuntu 18.04.  Please try it to see if it matches your glib version.
How did you determine the glib version? SO I can check the VMs I’m using.

I have a few bugs in the current HEAD, but when they are sorted, I’ll make a new release with instructions about how to build, for you to try.

- David
[JMLFloatingApprox.java.txt](https://github.com/OpenJML/OpenJML/files/7392475/JMLFloatingApprox.java.txt)
d

**Comment by davidcok** [comment]
Unit test added that this sample file successfully validates.
