### ISSUE TITLE
CRASH on simple java classes with latest version (0.16.0.alpha.8)

### ISSUE THREAD

**Issue by GorlemZ** [OpenJML/OpenJML#755]
```Pasting the error: 
jml -rac ass3/CF.java 
/home/andrea/Programs/openjml-ubuntu-latest-0.16.0-alpha-8/specs/java/lang/String.jml:939: Note: Not implemented for runtime assertion checking: ensures clause containing \fresh
      @   ensures \fresh(\result);
                        ^
/home/andrea/Programs/openjml-ubuntu-latest-0.16.0-alpha-8/specs/java/lang/String.jml:942: Note: Runtime assertion checking is not implemented for this type or number of declarations in a quantified expression
      @   ensures (\forall int i; 0 <= i < \result.length; \result[i] != null); // Including this avoids the needs for an instantiation, which is not always triggered
                   ^
/home/andrea/Programs/openjml-ubuntu-latest-0.16.0-alpha-8/specs/java/lang/String.jml:943: Note: Runtime assertion checking is not implemented for this type or number of declarations in a quantified expression
      @   ensures (\forall int i; 0 <= i < \result.length; \result[i] == split(this,regex,i));
                   ^
Internal JML bug - please report.  Build0.16.0-alpha-8
java.lang.AssertionError: typecode NONE
        at jdk.compiler/com.sun.tools.javac.jvm.Code.typecode(Code.java:261)
        at jdk.compiler/com.sun.tools.javac.jvm.Items$Item.coerce(Items.java:271)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:866)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:889)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1855)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1752)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:864)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitVarDef(Gen.java:1068)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:990)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlVariableDecl.accept(JmlTree.java:1463)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:669)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1084)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1054)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1405)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1697)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1508)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:669)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1084)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1054)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1405)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genTry(Gen.java:1500)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitTry(Gen.java:1488)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1401)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:669)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1084)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1054)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1405)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1697)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1508)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:669)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1084)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1054)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1405)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genTry(Gen.java:1500)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitTry(Gen.java:1488)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1401)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:669)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1084)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1054)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1405)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genTry(Gen.java:1500)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitTry(Gen.java:1488)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1401)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:669)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1084)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1054)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1405)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:669)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1084)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1054)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1405)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genTry(Gen.java:1500)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitTry(Gen.java:1488)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1401)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:618)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:669)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1084)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1054)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlBlock.accept(JmlTree.java:1405)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:632)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:954)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:917)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:900)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlMethodDecl.accept(JmlTree.java:1342)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:597)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2395)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:756)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1643)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1611)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:321)
        at jdk.compiler/org.jmlspecs.openjml.Main.compile(Main.java:533)
        at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:373)
        at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:331)
        at jdk.compiler/org.jmlspecs.openjml.Main.main(Main.java:294)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:53)

**Comment by davidcok** [comment]
Could you please add the offending source file to the report.
I’ll include this test and fix it — thanks.
But RAC is not to be considered robust in this version yet.

- David

**Comment by GorlemZ** [comment]
`
public class CF {
 
    public /*@ pure @*/static String codiceMese(int mese){
        switch(mese){
            case 1: return "A";
            case 2: return "B";
            case 3: return "C";
            case 4: return "D";
            case 5: return "E";
            case 6: return "H";
            case 7: return "L";
            case 8: return "M";
            case 9: return "P";
            case 10: return "R";
            case 11: return "S";
            case 12: return "T";
        }
        throw new IllegalArgumentException();
    }
 
    public  /*@ pure @*/ static String codiceCognome(String cognome) {
        return getConsonanti(cognome)
                .concat(getVocali(cognome))
                .concat("xxx")
                .substring(0,3);
    }
 
    public   /*@ pure @*/ static String codiceNome(String nome) {
 
        String n = nome.split(",")[0];
        String codice="";
        String consonanti=getConsonanti(n);
 
        if(consonanti.length()>=4){
            //prima terza quarta
            codice+=consonanti.charAt(0)+consonanti.charAt(2)+consonanti.charAt(3);
        }else{
            //come cognome
            codice=codiceCognome(nome);
        }
        return codice;
    }
 
    private   /*@ pure @*/ static String getConsonanti(String str){
        return str.replaceAll("[aeiou]", "");
 
    }
 
    private   /*@ pure @*/ static String getVocali(String str){
        return str.replaceAll("[^aeiou]", "");
    }
 
    public   /*@ pure @*/ static String codiceGiorno(int giorno, char sesso){
        if(sesso=='f'){
            giorno+=40;
        }
        return giorno<10 ? "0"+giorno : ""+giorno;
    }
 
    public   /*@ pure @*/ static String codiceAnno(int anno){
        return (anno%100)<10 ? "0"+anno : ""+anno;
 
    }
 
}

`
Thanks @davidcok

**Comment by davidcok** [comment]
With current openjml this no longer crashes, but does show some type checking errors in this class. Without a driver program (a main program) to run, I can't test this further.

**Comment by davidcok** [comment]
Closed this as no longer crashing (in OpenJML21)

**Comment by davidcok** [comment]
Needed an additional spec for String to enable ESC to succeed -- that all the array elements of the result satisfy their invariants
