### ISSUE TITLE
Problem with RAC assertion error line numbers

### ISSUE THREAD

**Issue by davidcok** [OpenJML/OpenJML#776]
The example in the OpenJMLUserGuide: examples/racreporting/A.java
yields the output

Exception in thread "main" java.lang.AssertionError: examples/racreporting/A.java:5: verify: JML Division by zero
      int j = i/(i-i);
               ^
	at java.base/org.jmlspecs.runtime.Utils.assertionFailureL(Utils.java:89)
	at A.main(A.java:1)

It is not clear why the line number is 1 instead of 5 in A.main(A.java:1)

It seems the line number is wrong when  --rac-java-checks is used but correct without it

**Comment by davidcok** [comment]
Created test in gitbug776, which showed the problem.

The bug was code like
		JCExpression c = M.at(pos).Apply(null, m, List.<JCExpression>of(sp, treeutils.makeStringLiteral(0, n))).setType(syms.voidType);

Here M.pos is first set to pos, then, within makeStringLiteral, it is set to 0, and then the Apply n ode is created, with the wrong position.

This is a likely common bug pattern -- a nested use of the same factory instance, and consequently out of order setting of position values.
