### ISSUE TITLE
"catastrophic JML internal error" with ESC on Google Guava

### ISSUE THREAD

**Issue by bauer-matthews** [OpenJML/OpenJML#785]
The following error occurs when running ESC on the Google Guava library. 

```
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Unexpected exception: Exception during parsing near ct object) {
        if (object instanceof StringConverter) {
   java.lang.NullPointerException: Cannot invoke "org.jmlspecs.openjml.IJmlClauseKind$ModifierKind.isTypeAnnotation()" because "ja.kind" is null
java.lang.NullPointerException: Cannot invoke "org.jmlspecs.openjml.IJmlClauseKind$ModifierKind.isTypeAnnotation()" because "ja.kind" is null
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.extractTypeAnnotations(JmlParser.java:369)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.formalParameter(JmlParser.java:385)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.formalParameters(JavacParser.java:4534)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.formalParameters(JavacParser.java:4526)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.formalParameters(JmlParser.java:403)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.methodDeclaratorRest(JavacParser.java:4409)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classOrInterfaceOrRecordBodyDeclaration(JavacParser.java:4273)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classOrInterfaceOrRecordBodyDeclaration(JmlParser.java:1196)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classInterfaceOrRecordBody(JavacParser.java:4154)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classInterfaceOrRecordBody(JmlParser.java:615)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3866)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classDeclaration(JmlParser.java:625)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classOrRecordOrInterfaceOrEnumDeclaration(JavacParser.java:3806)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classOrRecordOrInterfaceOrEnumDeclaration(JmlParser.java:443)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classOrInterfaceOrRecordBodyDeclaration(JavacParser.java:4205)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classOrInterfaceOrRecordBodyDeclaration(JmlParser.java:1196)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.enumBody(JavacParser.java:4051)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.enumDeclaration(JavacParser.java:3983)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classOrRecordOrInterfaceOrEnumDeclaration(JavacParser.java:3812)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classOrRecordOrInterfaceOrEnumDeclaration(JmlParser.java:443)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:3791)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:3635)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.parseCompilationUnit(JmlParser.java:265)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:620)
	at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.parse(JmlCompiler.java:211)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1009)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:996)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
	at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.compile(JmlCompiler.java:197)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:321)
	at jdk.compiler/org.jmlspecs.openjml.Main.compile(Main.java:534)
	at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:374)
	at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:332)
	at jdk.compiler/org.jmlspecs.openjml.Main.main(Main.java:295)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:53)
```

Steps to reproduce:

1. Clone the Google Guava library https://github.com/google/guava (as of this writing, the latest commit ID on `main` was d48418e4528ad0323e51e34d4e1044cc03c77c98)
2. From the root of the Guava repo, `cd guava`
3. Run `mvn clean compile` and `mvn dependency:copy-dependencies`
4. Run `openjml --class-path "target/dependency/*" --esc --dir guava/src/com/google/common/base --method "Strings.nullToEmpty"`
5. Observe the error above

**Comment by davidcok** [comment]
Put this issue on hold because the guava library would not build for me -- compile errors both with the most recent download and with the given commit-id.  With the stated commit, the java compiler (not openjml) crashes.
