### ISSUE TITLE
The return value of "com.sun.tools.javac.util.Context.get(java.lang.Class)" is null

### ISSUE THREAD

**Issue by Lewes** [OpenJML/OpenJML#786]
I am attempting to use the API in a project however I am unable to use the API. The project is running using the modified OpenJDK provided in the releases. I would appreciate any advice if the error is on my end.

My source code:
```
public class MainApp
{
    public static void main( String[] args ) throws Exception
    {
        IAPI api = Factory.makeAPI("-progress -verbose");
        api.execute(null, "-cp", "src/main/java/", "src/main/java/MaxBad.java");
    }
}
```

The error:
```
error: The compiler aborted with an uncaught exception: java.lang.NullPointerException: Cannot invoke "org.jmlspecs.openjml.IAPI$IProofResultListener.setListener(org.jmlspecs.openjml.IAPI$IProofResultListener)" because the return value of "com.sun.tools.javac.util.Context.get(java.lang.Class)" is null
java.lang.NullPointerException: Cannot invoke "org.jmlspecs.openjml.IAPI$IProofResultListener.setListener(org.jmlspecs.openjml.IAPI$IProofResultListener)" because the return value of "com.sun.tools.javac.util.Context.get(java.lang.Class)" is null
	at jdk.compiler/org.jmlspecs.openjml.Main.setProofResultListener(Main.java:645)
	at jdk.compiler/org.jmlspecs.openjml.Main.compile(Main.java:516)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
	at jdk.compiler/org.jmlspecs.openjml.Main.executeNS(Main.java:473)
	at jdk.compiler/org.jmlspecs.openjml.API.execute(API.java:222)
	at MainApp.main(MainApp.java:21)
```

My set-up:

- Macbook M1 macOS 13.0.1 (arm64)
- IntelliJ IDEA 2022.2.3 (however, error re-created using terminal using openjml script provided in releases).

**Comment by davidcok** [comment]
Confirmed that this is fixed -- see the test case OpenJmlTest/test/gitbug786
