### ISSUE TITLE
Cryptic exception when field spec contains invariant that is already violated at instantiation

### ISSUE THREAD

**Issue by bzp99** [OpenJML/OpenJML#807]
Consider this minimal example:

```
class Foo {
  //@ invariant foo > 0;
  int foo;
  Integer dummy = new Integer(12);
}
```

I think the invariant `foo > 0` can be considered bogus as it will be violated immediately when an instance of `Foo` is created and the JVM initializes `Foo#foo` to `0`. That said, the exception shown when compiling is misleading IMO:

```
$ openjml --rac Foo.java
EXCEPTION java.lang.NullPointerException: Cannot read field "sym" because "methodDecl" is null
java.lang.NullPointerException: Cannot read field "sym" because "methodDecl" is null
        at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.doSpecificationCase(JmlAssertionAdder.java:4918)
        at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder$SpecCaseIterator.hasNext(JmlAssertionAdder.java:4424)
        at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.applyHelper(JmlAssertionAdder.java:8726)
        at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitNewClass(JmlAssertionAdder.java:11740)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1807)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
        at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convertExpr(JmlAssertionAdder.java:1554)
        at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlVariableDecl(JmlAssertionAdder.java:19791)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlVariableDecl.accept(JmlTree.java:1517)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
        at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.visitJmlClassDecl(JmlAssertionAdder.java:15904)
        at jdk.compiler/org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1295)
        at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at jdk.compiler/org.jmlspecs.openjml.visitors.JmlTreeScanner.scan(JmlTreeScanner.java:70)
        at jdk.compiler/org.jmlspecs.openjml.esc.JmlAssertionAdder.convert(JmlAssertionAdder.java:1441)
        at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.rac(JmlCompiler.java:465)
        at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.flow(JmlCompiler.java:380)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
        at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.compile(JmlCompiler.java:197)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:321)
        at jdk.compiler/org.jmlspecs.openjml.Main.compile(Main.java:534)
        at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:374)
        at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:332)
        at jdk.compiler/org.jmlspecs.openjml.Main.main(Main.java:295)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:53)
Note: Foo.java uses or overrides a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
```

I did not look at the relevant piece of OpenJML code, but I think there should be block of logic that checks for such problems and fails the build with a message along the lines of _Foo.java:2: invariant does not always hold._

For the record, I encountered this with v0.17.0-alpha-15.

**Comment by bzp99** [comment]
I forgot to mention that the `dummy` field is necessary to reproduce the error. It only seems to occur when an object is instantiated using a constructor in one of the fields.

**Comment by davidcok** [comment]
Reproduced this for OpenJML17. Confirmed that it is fixed in OpenJML21. Added a test to be sure it stays fixed.
