### ISSUE TITLE
Catastrophic failure during processing of input file

### ISSUE THREAD

**Issue by gabrielestentella** [OpenJML/OpenJML#809]
I've installed the OpenJML Eclipse plug-in using The OpenJML Eclipse Update Site.
I'm using:
JRE System Library Java 1.8.333.02
Eclipse Version: 2023-09 (4.29.0)

When I try to compile every java class I see an error like the following:

```
[0.00] Executing openjml on Parent.java
error: Catastrophic failure during processing of input file

Internal JML bug - please report.  BuildOpenJML-0.8.59-20211116
java.lang.NullPointerException: Cannot read field "elems" because "tree.starImportScope" is null
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:502)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.comp.JmlEnter.main(JmlEnter.java:834)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:992)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:864)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:582)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.executeNS(Main.java:508)
	at org.jmlspecs.openjml.API.execute(API.java:223)
	at org.jmlspecs.openjml.eclipse.OpenJMLInterface.executeExternalCommand(OpenJMLInterface.java:293)
	at org.jmlspecs.openjml.eclipse.Utils$4.run(Utils.java:676)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
ENDING with exit code 4
INTERNAL ERROR: return code = 4   Command: -command=rac -lang=jml+ -purityCheck=false -show=false -racShowSource=true -racCheckAssumptions=false -racPreconditionEntry=false -racJavaChecks=false -racCompileToJavaAssert=false -verboseness=2 -checkSpecsPath -nullableByDefault=false -no-internalSpecs -specspath /Users/gabriele/Desktop/PSS/Lab/exercise1/src:/Applications/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/513/0/.cp/specs -sourcepath /Users/gabriele/Desktop/PSS/Lab/exercise1/src -no-internalRuntime -classpath /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/resources.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/rt.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jsse.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jce.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/charsets.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jfr.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/sunec.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/nashorn.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/cldrdata.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/jfxrt.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/dnsns.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/localedata.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/sunjce_provider.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/sunpkcs11.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/jaccess.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext/zipfs.jar:/Users/gabriele/Desktop/PSS/Lab/exercise1/src:/Applications/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/511/0/.cp/jmlruntime.jar:/Applications/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/511/0/.cp/jmlruntime.jar -d /Users/gabriele/Desktop/PSS/Lab/exercise1/bin /Users/gabriele/Desktop/PSS/Lab/exercise1/src/Parent.java
```
I used [this example](https://github.com/OpenJML/OpenJML/blob/master/OpenJMLTest/testfiles/escConstructor/Parent.java)

**Comment by davidcok** [comment]
The Eclipse plugin (which only supported Java 8) is unsupported at the moment. This examples works OK (via command-line, with adjustments for changes in options) for OpenJML17 and 21.
