### ISSUE TITLE
jmlspecs.annotation crashes

### ISSUE THREAD

**Issue by pys** [OpenJML/OpenJML#812]
I was not lucky at my first trial to use
org.jmlspecs.annotation
Here are the error messages:
~/src/openjml-jun22/openjml -esc ~/src/IdeaProjects/jan24/src/BinaryTree.java
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Unexpected exception: Exception during parsing near Tree left, @NonNull BinaryTree right, int r) {
          root  java.lang.NullPointerException: Cannot invoke "org.jmlspecs.openjml.IJmlClauseKind$ModifierKind.isTypeAnnotation()" because "ja.kind" is null
java.lang.NullPointerException: Cannot invoke "org.jmlspecs.openjml.IJmlClauseKind$ModifierKind.isTypeAnnotation()" because "ja.kind" is null
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.extractTypeAnnotations(JmlParser.java:369)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.formalParameter(JmlParser.java:385)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.formalParameters(JavacParser.java:4534)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.formalParameters(JavacParser.java:4526)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.formalParameters(JmlParser.java:403)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.methodDeclaratorRest(JavacParser.java:4409)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classOrInterfaceOrRecordBodyDeclaration(JavacParser.java:4254)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classOrInterfaceOrRecordBodyDeclaration(JmlParser.java:1196)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classInterfaceOrRecordBody(JavacParser.java:4154)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classInterfaceOrRecordBody(JmlParser.java:615)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3866)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classDeclaration(JmlParser.java:625)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classOrRecordOrInterfaceOrEnumDeclaration(JavacParser.java:3806)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.classOrRecordOrInterfaceOrEnumDeclaration(JmlParser.java:443)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:3791)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:3635)
	at jdk.compiler/com.sun.tools.javac.parser.JmlParser.parseCompilationUnit(JmlParser.java:265)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:620)
	at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.parse(JmlCompiler.java:211)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1009)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:996)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
	at jdk.compiler/com.sun.tools.javac.main.JmlCompiler.compile(JmlCompiler.java:197)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:321)
	at jdk.compiler/org.jmlspecs.openjml.Main.compile(Main.java:534)
	at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:374)
	at jdk.compiler/org.jmlspecs.openjml.Main.execute(Main.java:332)
	at jdk.compiler/org.jmlspecs.openjml.Main.main(Main.java:295)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:53)
1 error
---- and my Java+JML file  ---
import org.jmlspecs.annotation;
public /*@ nullable_by_default @*/ class BinaryTree {

    Node root;

    private  class Node {
        Node left;
        Node right;
        int val;
    }

    // Empty Binary Tree
    //@ pure
    BinaryTree() {
        root = null; //by default anyway
    }
    //Single-Node Binary Tree
    //@ pure
    BinaryTree(int r) {
        root = new Node();
        root.val = r; //left, right are null
    }

    //Usual constructor for Binary Tree: adds 1 node above existing ones.
    //@ pure
    BinaryTree(@NonNUll BinaryTree left, @NonNull BinaryTree right, int r) {
        root = new Node();
        root.val = r;
        root.left = left.root;
        root.right = right.root;
    }
    /*@ requires depth >= 0;
   @ measured_by depth;
   @ normal_behaviour
   @ requires n == null;
   @ ensures \result == (depth <= 1);
   @ normal_behaviour
   @ requires n != null;
   @ requires depth>0;
   @ ensures  \result == (allNullAtOrPred(n.left,depth-1)&&
                   allNullAtOrPred(n.right,depth-1));
   @ normal_behaviour
   @ requires n != null;
   @ requires depth == 0;
  @ ensures  \result == false;
       pure @*/
    boolean allNullAtOrPred(Node n, int depth) {
        if(n == null) return (depth <= 1);
        else if(depth>0)
            return allNullAtOrPred(n.left,depth-1)&&
                    allNullAtOrPred(n.right,depth-1);
        else return false;
    }

    /*@ ensures \result == (\exists int n;  n >= 0;
                             allNullAtOrPred(root,n));
     pure @*/
    boolean allNullAtNearlySameLevel() 
    {return depthOfNull(root).size() <= 1;};

    private @NonNull
    class Interval {
        int min;
        int max;

        //@ pure
        public Interval(int i, int j) {
            min = i;
            max = j;
        }
        // min > max means an empty interval. We suggest to normalize it to 1,0.
        //@ pure

        public int size() {
            if(max >= min) return max-min+1;
            return 0;
        }
    }
/*@ pure
*/
    Interval depthOfNull(Node n) {
        if(n==null) return new Interval(0,0);
        Interval ileft = depthOfNull(n.left);
        Interval iright = depthOfNull(n.right);
        return new Interval(1+Math.min(ileft.min, iright.min),1+Math.max(ileft.max, iright.max));
    }
}

**Comment by davidcok** [comment]
Granted, it should not crash, but the immediate problem is that NonNull is misspelled as NonNUll in one spot.

After that, you won't crash, but
a) your import statement needs to be 'import org.jmlspecs.annotation.*;'
b) line 62: replace @NonNull by @NonNullByDefault

**Comment by pys** [comment]
Thanks -- and agreed, my file is silly.
I have another question: for classes BinaryTree and Interval, I would like to say 'Whenever this class is used, even if the current default is nullable, the declaration should be considered non_null'. Is there a way to say that in JML? You proposed @NonNullByDefault but it works only inside the class, and sets the default also for other classes used there.

**Comment by davidcok** [comment]
You can always annotate a type in a declaration as @NonNull even if the surrounding default is @Nullable (or vice versa)

@NonNullByDefault sets the default for declarations within the class, as you stated (not uses of the class name in other declarations)

**Comment by davidcok** [comment]
This issue has been made into a test, with the obvious syntax errors fixed. Intervening changes have solved the crash problem  Now the class typechecks successfully. Attempts to do verification run into two problems: insufficient information about when something is null and potential arithmetic overflows. Will leave those errors as representative of the original issue. I'll create a separate test (gitbug812a) in which (eventually), with additional specifications,  a fully successful verification is accomplished.

**Comment by davidcok** [comment]
Issue #842 added -- embellish specs (gitbug812a) to make verification successful.
